INSERT INTO acm_evidences (element_id, name, definition) VALUES
	(1, 'Self Emotional Awareness', 'Kemampuan untuk mengenali dan memahami emosi pribadi, termasuk mengidentifikasi emosi yang muncul, memahami penyebabnya, dan mengenali bagaimana emosi mempengaruhi perilaku dan pikiran.'),
	(1, 'Self Control', 'Kemampuan untuk mengendalikan respons emosional secara efektif, termasuk mengelola kemarahan, frustasi, dan stres dengan cara yang sehat, dan menghindari tindakan impulsif yang dapat merugikan diri sendiri atau orang lain.'),
	(1, 'Stress Management', 'Kemampuan untuk mengenali dan mengatasi stres dengan strategi yang efektif, seperti relaksasi, olahraga, meditasi, atau teknik pengelolaan stres lainnya.'),
	(1, 'Empathic', 'Kemampuan untuk memahami dan menghargai emosi orang lain, dan mengelola interaksi sosial dengan kepekaan emosional yang baik.'),
	(1, 'Emotional Resilience', 'Kemampuan untuk pulih dari kegagalan, kesulitan, atau tantangan emosional dengan cepat dan efektif, serta mampu mengadaptasi diri dengan perubahan dan tekanan yang timbul.'),

	(2, 'Emotional Awareness', 'Kesadaran akan perasaan dan emosi yang sedang dialami.'),
	(2, 'Emotion v.s. Behavior', 'Pemahaman tentang bagaimana emosi mempengaruhi keputusan dan tindakan.'),
	(2, 'Emotional Pattern Recognition', 'Kemampuan untuk mengenali pola emosional dan reaksi terhadap situasi tertentu.'),
	(2, 'Self Appreciation', 'Penerimaan dan penghargaan terhadap kekuatan dan kelemahan emosional diri sendiri.'),
	(2, 'Emotion v.s. Interpersonal Relationship', 'Kesadaran tentang bagaimana emosi mempengaruhi hubungan interpersonal.'),

	(3, 'Healthy & Appropriate', 'Kemampuan untuk meresapi dan mengekspresikan emosi secara sehat dan tepat.'),
	(3, 'Effective Strategy', 'Pemahaman tentang strategi dan teknik pengelolaan emosi yang efektif.'),
	(3, 'Negative Emotional Impact', 'Kesadaran akan dampak situasi emosional negatif pada personal dan sosial.'),
	(3, 'Being Calm & Focused', 'Kemampuan untuk tetap tenang dan fokus dalam situasi yang menegangkan atau menantang.'),
	(3, 'Flexibility', 'Fleksibilitas dalam menyesuaikan diri dengan perubahan dan situasi yang berbeda.'),
	(4, 'Built-in', 'TBD'),

	(5, 'Identify Stress', 'Kemampuan untuk mengenali tanda-tanda stres dan mengidentifikasi pemicunya.'),
	(5, 'Relaxation Technique', 'Keahlian dalam menggunakan teknik relaksasi, seperti meditasi atau pernapasan dalam, untuk mengurangi stres.'),
	(5, 'Positive Thinking', 'Kemampuan untuk mengelola pikiran negatif dan menggantinya dengan pola pikir yang lebih positif.'),
	(5, 'Coping Strategy', 'Penggunaan strategi penyesuaian, seperti mengatur ekspektasi yang realistis atau mengambil istirahat yang cukup, untuk mengurangi stres.'),
	(5, 'Support & Assistance', 'Kemampuan untuk meminta dukungan dan bantuan dari orang lain saat menghadapi situasi yang menimbulkan stres.'),

	(6, 'Social Emotional Awareness', 'Kemampuan untuk mengenali dan memahami dan menghargai emosi orang lain dalam konteks sosial.'),
	(6, 'Empathic', 'Kemampuan untuk memahami dan merasakan emosi orang lain, dan merespons secara empatik dengan kepekaan dan perhatian.'),
	(6, 'Self Regulation', 'Kemampuan untuk mengelola dan mengatur respon emosional secara efektif dalam situasi sosial, termasuk mengendalikan emosi yang dapat mempengaruhi interaksi.'),
	(6, 'Effective Emotional Communication', 'Kemampuan untuk menyampaikan emosi dengan jelas dan terbuka, serta mendengarkan dengan empati dalam komunikasi sosial.'),
	(6, 'Building Healthy Relationships', 'Kemampuan untuk membangun dan mempertahankan hubungan yang sehat dengan orang lain, termasuk membangun kepercayaan, mendukung, dan memahami kebutuhan dan harapan orang lain.'),

	(7, 'Social Cue Awareness', 'Kesadaran terhadap isyarat verbal dan nonverbal yang menunjukkan emosi orang lain.'),
	(7, 'Social Cue Recognitions', 'Kepekaan terhadap ekspresi wajah, bahasa tubuh, dan nada suara orang lain.'),
	(7, 'Differentiating Emotions', 'Kemampuan untuk membedakan antara beragam emosi yang berbeda.'),
	(7, 'Emotional Impact Awareness', 'Pemahaman tentang bagaimana emosi mempengaruhi perilaku orang lain.'),
	(7, 'Interpreting Emotional Signals', 'Keterampilan dalam menginterpretasi isyarat emosional dalam berbagai situasi.'),

	(8, 'Understanding Others Perspectives', 'Kemampuan untuk melihat situasi dari sudut pandang dan/atau posisi orang lain.'),
	(8, 'Empathic Appreciation', 'Menghargai dan mengakui perasaan, pikiran, dan pengalaman orang lain.'),
	(8, 'Validating Emotions', 'Pemahaman pentingnya validasi emosi dalam membangun hubungan yang kuat.'),
	(8, 'Emphatic Support', 'Keterampilan dalam menunjukkan dukungan dan pengakuan terhadap perasaan orang lain.'),
	(8, 'Safe & Supportive', 'Kemampuan untuk menciptakan lingkungan yang aman dan mendukung untuk berbicara tentang emosi.'),

	(9, 'Flexibility', 'Mampu mengubah pendekatan atau rencana mereka untuk menyesuaikan diri dengan perubahan, tidak terpaku pada satu cara melakukan sesuatu dan terbuka untuk mencoba metode baru.'),
	(9, 'Continuous Learning', 'Komitmen untuk belajar dan pengembangan berkelanjutan dan mampu belajar dari kesalahan dan kegagalan, serta mengambil pelajaran dari pengalaman.'),
	(9, 'Creative Solutions', 'Mencari solusi kreatif untuk masalah dan tantangan, dan tidak takut untuk mencoba pendekatan baru atau inovatif.'),
	(9, 'Stress Tolerances', 'Mampu bekerja efektif bahkan di bawah tekanan atau dalam situasi yang sulit, dan mampu mengendalikan emosi dan tetap fokus pada tujuan meskipun menghadapi hambatan.'),
	(9, 'Resilience', 'Kemampuan untuk pulih dari tekanan, stres, atau kegagalan, tidak mudah jatuh dalam situasi yang sulit dan mampu bangkit kembali dengan cepat.'),
	(10, 'Built-in', 'TBD'),

	(11, 'Openmind', 'Menerima dengan terbuka ide, pendapat, dan perspektif yang berbeda dari anggota tim lainnya.'),
	(11, 'Avoid Biases', 'Menghindari prasangka dan sikap defensif terhadap gagasan baru.'),
	(11, 'Empathic', 'Menempatkan diri dalam posisi orang lain dan mencoba memahami sudut pandang mereka.'),
	(11, 'Valuing Differencies', 'Mengakui bahwa pemikiran yang berbeda dapat membawa nilai tambah dan inovasi.'),
	(11, 'Williness to Change', 'Bersedia untuk merevisi dan mengubah pendapat berdasarkan argumen yang kuat.'),

	(12, 'Perpectives Flexibility', 'Kemampuan untuk mengubah sudut pandang dan berpikir secara terbuka terhadap ide-ide baru.'),
	(12, 'Embracing Differecies', 'Menerima perbedaan sebagai kesempatan untuk belajar dan tumbuh.'),
	(12, 'Adaptability', 'Kemampuan untuk menyesuaikan rencana dan strategi saat situasi memerlukan.'),
	(12, 'New Pattern Recognition', 'Keterampilan dalam mengidentifikasi pola-pola baru atau peluang dalam lingkungan yang berubah.'),
	(12, 'Willingness to Change', 'Bersedia untuk keluar dari zona nyaman dan menghadapi tantangan baru.'),

	(13, 'Being Critical', 'Mengkaji kembali keputusan dan tindakan yang diambil untuk mengevaluasi keefektifannya.'),
	(13, 'Self Assessment', 'Mengevaluasi kekuatan dan kelemahan pribadi dalam pemikiran dan pengambilan keputusan'),
	(13, 'Challenging Beliefs', 'Mempertanyakan keyakinan dan asumsi yang mendasari pemikiran dan pengambilan keputusan.'),
	(13, 'Identify Bias', 'Mengidentifikasi bias atau kecenderungan pribadi yang dapat mempengaruhi pemikiran kritis.'),
	(13, 'Develop Introspective Ablilities', 'Mengembangkan kemampuan introspeksi untuk memahami motivasi, nilai-nilai, dan tujuan pribadi yang mempengaruhi pemikiran dan tindakan.'),

	(14, 'Comfortability', 'Merasa nyaman dalam menghadapi ketidakpastian dan situasi yang tidak jelas.'),
	(14, 'Adaptability', 'Mampu beradaptasi dengan perubahan dan kondisi yang tidak terstruktur.'),
	(14, 'Courage', 'Berani menjelajahi ruang keputusan yang ambigu dan tidak memiliki jawaban yang jelas.'),
	(14, 'Facing Complexity', 'Menghadapi kompleksitas dengan ketenangan dan keberanian.'),
	(14, 'Uncertainty v.s Opportunity', 'Melihat ketidakpastian sebagai peluang untuk inovasi dan eksplorasi.'),

	(15, 'Time Management', 'Kemampuan untuk mengatur waktu dengan bijaksana antara pekerjaan dan kehidupan pribadi.'),
	(15, 'Setting Time Norms', 'Keahlian dalam menetapkan batasan dan menghormati waktu untuk kehidupan pribadi.'),
	(15, 'Prioritizing', 'Kemampuan untuk memprioritaskan kegiatan yang memberikan kepuasan di kedua bidang tersebut.'),
	(15, 'Flexibility', 'Fleksibilitas dalam menyesuaikan jadwal kerja untuk mengakomodasi kebutuhan pribadi.'),
	(15, 'Burnout Awareness', 'Kemampuan untuk menghindari kelelahan dan kejenuhan dengan menciptakan waktu untuk kegiatan refreshing dan rekreasi.'),

	(16, 'Ambition', 'Keinginan kuat untuk berhasil dan berusaha mencapai tujuan yang mereka tetapkan, sering memiliki tujuan jangka panjang dan pendek dan terus mendorong diri sendiri untuk mencapainya.'),
	(16, 'Determination & Persistence', 'Penuh tekad, bahkan ketika dihadapkan dengan rintangan dan tantangan, terus berusaha mencari solusi, bukan fokus pada masalah.'),
	(16, 'Initiative', 'Proaktif dan cenderung mengambil tindakan tanpa perlu dipaksa, mengidentifikasi peluang atau tantangan dan bertindak sesuai dengan kebutuhan, tanpa menunggu instruksi.'),
	(16, 'Pursuit of Excellence', 'Selalu berusaha melakukan yang terbaik dan merasa tidak puas dengan hasil yang kurang dari itu, berupaya mencapai standar yang lebih tinggi.'),
	(16, 'Resilience', ' Kekuatan dalam menghadapi kegagalan dan rintangan, kegagalan sebagai peluang untuk belajar dan mengembangkan diri, cepat pulih dab bangkit dari kegagalan.'),
	(17, 'Built-in', 'TBD'),

	(18, 'Positivism', 'Menghadapi kegagalan dengan sikap positif dan belajar dari kesalahan'),
	(18, 'Emotional Endurance', 'Menunjukkan ketahanan emosional dalam menghadapi tekanan dan stres'),
	(18, 'Highly Motivated', 'Mempertahankan motivasi dan semangat meskipun menghadapi rintangan'),
	(18, 'Strategy', 'Mengembangkan strategi untuk mengatasi hambatan dan mengubah tantangan menjadi peluang'),
	(18, 'Adaptive & Focused', 'Menyesuaikan diri dengan perubahan dan tetap fokus pada pencapaian tujuan'),

	(19, 'Determined', 'Gigih dan memiliki tekad yang kuat untuk mencapai tujuan mereka, meskipun menghadapi hambatan.'),
	(19, 'Intrinsic Motivation', 'Motivasi intrinsik yang tinggi untuk mencapai tujuan.'),
	(19, 'Goal Focused', 'Fokus pada tujuan dan tidak mudah terganggu oleh hambatan atau distraksi.'),
	(19, 'Never Give Up', ' Pantang menyerah, akan mencoba lagi dan lagi sampai berhasil.'),
	(19, 'Hardworking', 'Bekerja keras dan melakukan apa pun yang diperlukan untuk mencapai tujuan mereka.'),

	(20, 'Ambiguity Tolerance', 'Merasa nyaman dalam menghadapi ketidakpastian dan situasi yang tidak jelas.'),
	(20, 'Adaptability', 'Mampu beradaptasi dengan perubahan dan kondisi yang tidak terstruktur.'),
	(20, 'Courage', 'Berani menjelajahi ruang keputusan yang ambigu dan tidak memiliki jawaban yang jelas.'),
	(20, 'Complexity Tolerance', 'Menghadapi kompleksitas dengan ketenangan dan keberanian.'),
	(20, 'Uncertainty v.s. Opportunity', 'Melihat ketidakpastian sebagai peluang untuk inovasi dan eksplorasi.'),

	(21, 'Courage', ' Berani mengambil risiko dalam mencoba ide atau pendekatan baru'),
	(21, 'Opportunity Seeker', 'Mengidentifikasi peluang atau kesempatan yang mungkin belum dilihat oleh orang lain'),
	(21, 'Creative & Innovative', 'Menerapkan pemikiran kreatif dan inovatif dalam menghadapi tantangan'),
	(21, 'Proactive', 'Menunjukkan proaktif dalam mengatasi masalah atau hambatan'),
	(21, 'Take Responsibility', 'Mengambil tanggung jawab penuh atas inisiatif yang diambil dan hasil yang dihasilkan'),

	(22, 'Self Confidence', 'Percaya pada kemampuan diri sendiri untuk menyelesaikan tugas atau mengatasi masalah'),
	(22, 'Independence', 'Mengambil keputusan yang bijaksana tanpa bergantung pada bantuan atau arahan orang lain'),
	(22, 'Accountability', 'Bertanggung jawab atas tindakan dan keputusan yang diambil'),
	(22, 'Time & Resource Management', 'Mengelola waktu dan sumber daya dengan efisien untuk mencapai tujuan'),
	(22, 'Adaptability', 'Mampu bekerja dalam situasi yang tidak pasti atau dengan informasi yang terbatas'),

	(23, 'Goal Identification', 'Mengidentifikasi apa yang mereka inginkan untuk dicapai, baik dalam jangka pendek maupun jangka panjang, memahami apa yang penting dan apa yang dibutuhkan untuk puas dan berhasil.'),
	(23, 'Planning', 'Merumuskan rencana untuk mencapainya, melibatkan pemecahan tujuan menjadi langkah-langkah yang lebih kecil dan dapat dikelola, dan penciptaan jadwal atau batas waktu untuk mencapainya.'),
	(23, 'Motivating', 'Melibatkan motivasi diri sendiri untuk bekerja menuju tujuan tersebut, termasuk pencarian cara untuk tetap termotivasi saat menghadapi hambatan atau kesulitan.'),
	(23, 'Progress & Adjustment', 'Melacak kemajuan terhadap tujuan dan melakukan penyesuaian jika diperlukan, melibatkan penyesuaian rencana atau tujuan jika situasi berubah.'),
	(23, 'Time & Resource Management', 'mengatur waktu dan sumber daya secara efektif adalah bagian penting dari penetapan tujuan, mampu menyeimbangkan berbagai tuntutan dan memprioritaskan tugas untuk mencapai tujuan mereka.'),

	(24, 'Opportunity Identification', 'Kemampuan untuk melihat peluang dan mengembangkan solusi kreatif dalam situasi yang berubah.'),
	(24, 'Risk Assessment', 'Keahlian dalam mengevaluasi risiko dan keuntungan dari setiap solusi yang mungkin.'),
	(24, 'Quick and Decisive Action', 'Kemampuan untuk mengambil tindakan cepat dan tepat ketika menghadapi perubahan atau ketidakpastian.'),
	(24, 'Flexibility', 'Fleksibilitas dalam mengubah rencana jika diperlukan untuk mencapai hasil yang diinginkan.'),
	(24, 'Utilizing Technology and Resources', 'Kemampuan untuk memanfaatkan teknologi atau sumber daya lainnya untuk mendukung solusi yang diusulkan.'),

	(25, 'Output Driven', 'Berfokus pada pencapaian hasil yang diinginkan'),
	(25, 'Progress Monitoring', 'Memonitor kemajuan dan mengukur kinerja secara berkala'),
	(25, 'Gap Analysis', 'Menganalisis kesenjangan antara hasil yang diharapkan dan aktual'),
	(25, 'Taking Action', 'Mengambil tindakan yang diperlukan untuk mencapai atau melampaui standar kinerja yang ada'),
	(25, 'Seeking Feedback', 'Mencari umpan balik dan belajar dari kesalahan untuk meningkatkan kinerja'),

	(26, 'Motivation to Learn', 'Dorongan intrinsik memperoleh pengetahuan dan keterampilan baru.'),
	(26, 'Self Improvement', 'Dorongan  kuat untuk terus-menerus meningkatkan diri, apakah itu pengetahuan, keterampilan, atau pemahaman tentang dunia.'),
	(26, 'Adaptability', ' Kemampuan menyesuaikan diri dengan perubahan dan belajar dari pengalaman baru'),
	(26, 'Reflection and Introspection', 'Kemampuan melibatkan proses belajar dari pengalaman sebelumnya, baik keberhasilan maupun kegagalan. '),
	(26, 'Experimentation', 'Bereksperimen dengan ide dan pendekatan baru, dan belajar dari hasil eksperimen tersebut.'),

	(27, 'Indepth Inquiries', 'Mempertanyakan dan mencari pemahaman yang lebih dalam tentang topik atau situasi'),
	(27, 'Openmind', 'Terbuka untuk ide dan perspektif baru'),
	(27, 'Enthusiasm', 'Menunjukkan antusiasme dalam mengeksplorasi hal-hal baru'),
	(27, 'Acknowledge Ignorance', 'Tidak takut untuk mengakui ketidaktahuan dan bertanya'),
	(27, 'Continuous Learning', 'Proaktif dan berkelanjutan mengembangkan dan meningkatkan pengetahuan, keterampilan, dan kompetensi '),

	(28, 'Time Allocation', 'Meluangkan waktu untuk pembacaan, penelitian, dan diskusi'),
	(28, 'Active Participation', 'Aktif berpartisipasi dalam pelatihan atau kursus'),
	(28, 'Seeking Guidance', 'Mencari bimbingan dan nasihat dari orang yang lebih berpengalaman'),
	(28, 'Curiosity', 'Berusaha memahami beragam pengetahuan, konsep dan teori baru'),
	(28, 'Networking', 'Membangun jaringan dengan para ahli dalam bidang yang diminati'),

	(29, 'New Approach', 'Mencoba pendekatan baru, teknik, atau alat dalam rangka mencari solusi yang lebih baik.'),
	(29, 'Experiential Learning', 'Belajar dari kegagalan dan kesuksesan dalam proses eksperimen.'),
	(29, 'Risk Taker', 'Berani mengambil risiko dan mencari tahu apa yang berhasil dan apa yang tidak.'),
	(29, 'Openmind', 'Membangun sikap terbuka terhadap berbagai pendekatan dan ide baru.'),
	(29, 'Adaptability', 'Mengadaptasi dan memperbaiki eksperimen berdasarkan hasil dan umpan balik yang diperoleh.'),

	(30, 'Literal Interpretation', 'Kemampuan memahami dan menafsirkan informasi sesuai dengan arti sebenarnya atau harfiah, tidak menginterpretasi yang lebih dalam atau abstrak.'),
	(30, 'Detail Oriented', 'Fokus pada detail-detail spesifik dan dapat diamati dari suatu situasi atau objek, sebaliknya dari melihat gambaran besar atau konsep abstrak.'),
	(30, 'Fact-Based Reasoning', 'Menggunakan data atau fakta yang nyata dan dapat diverifikasi untuk membuat kesimpulan atau keputusan, daripada mengandalkan intuisi, perkiraan, atau konsep teoretis.'),
	(30, 'Sequential Thinking', 'Berpikir dalam urutan langkah-langkah yang logis dan terstruktur, seringkali mengikuti proses atau aturan yang sudah ditentukan.'),
	(30, 'Practical Solution', 'Menggunakan pendekatan yang praktis dan langsung dalam menyelesaikan masalah, mengandalkan solusi yang terbukti dan efektif.'),

	(31, 'Abstract Thinking', 'Berpikir dalam level abstrak, bukan hanya konkret, melibatkan pemahaman tentang prinsip, teori, atau konsep yang mendasari.'),
	(31, 'Unconventional Thinking', 'Mengidentifikasi berbagai kemungkinan dan pendekatan, dan tidak dibatasi oleh pemikiran konvensional.'),
	(31, 'Seeing "Big Picture"', 'Melihat "gambaran besar" dan memahami bagaimana bagian-bagian individu berinteraksi dalam konteks yang lebih luas.'),
	(31, 'Conceptual Interoperability', 'Menengarai bagaimana ide-ide, konsep, pola, dan masalah saling terhubung. '),
	(31, 'Reality Checking', 'Mengkaitkan dan mengevaluasi hasil pemikiran konseptual dengan fenomena atau situasi dunia nyata.'),
	(32, 'Built-in', 'TBD'),

	(33, 'Condition Recognition', 'Kemampuan untuk memahami dan mengidentifikasi situasi/kondisi/informasi yang ada.'),
	(33, 'Decomposition', 'Memecah situasi/kondisi/informasi menjadi komponen,unsur, atau bagian yang lebih kecil.'),
	(33, 'Pattern Analysis', 'Kemampuan menganalisis trend, pola ataupun interaksi antar unsur atau komponen dan kontribusinya terhadap situasi/kondisi.'),
	(33, 'Cause-Effect Analysis ', 'Kemampuan menentukan hubungan sebab-akibat antara unsur-unsur atau komponen.'),
	(33, 'Hypothesis Making', 'Membuat hipotesis atau teori berdasarkan pola dan hubungan yang telah ditemukan.'),
	(34, 'Built-in', 'TBD'),

	(35, 'Logical Reasoning', 'Menerapkan pemikiran logis dalam mengevaluasi argumen dan bukti.'),
	(35, 'Identify Cause-Effect Relationship', 'Mengidentifikasi hubungan sebab-akibat dan implikasi logis dari informasi yang diberikan.'),
	(35, 'Premises Validity', 'Menggunakan premis yang valid dan menghasilkan kesimpulan yang logis.'),
	(35, 'Avoid Logical Fallacies & Overgeneralizations', 'Menghindari kesalahan logika yang umum, seperti pemikiran hitam-putih atau generalisasi berlebihan.'),
	(35, 'Develop Valid Argumentation', 'Menyusun argumen dengan runtut dan konsisten.'),

	(36, 'Think Abstractly', 'Mampu berpikir secara abstrak dan konseptual dalam memecahkan masalah.'),
	(36, 'Deductive/Inductive Reasoning', 'Menerapkan pemikiran deduktif dan induktif untuk menarik kesimpulan dan membuat prediksi.'),
	(36, 'Pattern & Relationship', 'Mengidentifikasi pola, hubungan, dan prinsip yang mendasari data atau informasi.'),
	(36, 'Logical Analysis', 'Menggunakan logika dan analisis untuk memecahkan masalah yang kompleks.'),
	(36, 'Broadmind', 'Melihat masalah dari perspektif yang lebih luas dan mengenali implikasi yang lebih dalam.'),

	(37, 'Information Gatherings', 'Mengumpulkan informasi dari berbagai sumber yang relevan.'),
	(37, 'Analyse & Evaluate', 'Menganalisis dan mengevaluasi informasi untuk memahami konteks dan implikasinya.'),
	(37, 'Identify Pattern & Trend', 'Mengidentifikasi pola, tren, atau hubungan yang muncul dari informasi yang dikumpulkan.'),
	(37, 'Combine Concrete & Abstract Information', 'Menggabungkan informasi konkret dan abstrak untuk menciptakan pemahaman yang lebih komprehensif.'),
	(37, 'Applying the Synthesized Information', 'Mengaplikasikan informasi yang disintesa dalam pemecahan masalah atau pengambilan keputusan.'),

	(38, 'Gather & Evaluate Evidence', 'Mengumpulkan dan mengevaluasi bukti yang relevan untuk mendukung pengambilan keputusan.'),
	(38, 'Evidence Reliability & Validity', 'Memeriksa keandalan, validitas, dan relevansi bukti yang ada.'),
	(38, 'SWOT the Evidences', 'Menggunakan pendekatan objektif dalam menilai kekuatan dan kelemahan bukti.'),
	(38, 'Identify Biases/Tendencies', 'Mengidentifikasi bias atau kecenderungan dalam bukti yang dapat mempengaruhi penilaian.'),
	(38, 'Develop Strong& Accountable Evidences', 'Menggunakan bukti yang kuat dan dapat dipertanggungjawabkan untuk mendukung argumen atau keputusan.'),

	(39, 'Summarize Analysis & Interpretation', 'Menyimpulkan hasil analisis dan interpretasi data dengan tepat.'),
	(39, 'Interoperability: Issues v.s. Conclusions', 'Menghubungkan kesimpulan dengan pertanyaan atau masalah yang sedang dihadapi.'),
	(39, 'Conclusion Validity & Reliability', 'Memastikan kesimpulan didasarkan pada bukti yang kuat dan logika yang benar.'),
	(39, 'Direct v.s Indirect Assumptions', 'Membedakan antara kesimpulan yang jelas (direct assumptions) dan dugaan tidak langsung (indirect assumptions)'),
	(39, 'Acknowledge Limitiations', 'Mengakui keterbatasan dan ketidakpastian dalam pengambilan kesimpulan.'),

	(40, 'Recognizing Personal Biases', 'Mengakui adanya bias pribadi, pendapat praduga, atau preferensi yang dapat mempengaruhi pemikiran dan pengambilan keputusan.'),
	(40, 'Maintain Common Biases', 'Menjaga kewaspadaan terhadap bias yang umum, seperti bias konfirmasi atau bias pemilihan informasi.'),
	(40, 'Accept Difference Perspectives', 'Menerima sudut pandang dan perspektif yang berbeda, serta mencari cara untuk mengurangi dampak bias dalam pemikiran.'),
	(40, 'Check Underlying Assumtions', 'Memeriksa asumsi yang mendasari dan menguji kebenarannya secara kritis.'),
	(40, 'Manage Critical Questions', 'Mengajukan pertanyaan yang kritis dan menggali lebih dalam untuk memahami implikasi dari sudut pandang yang berbeda.'),

	(41, 'Abstract Concept Understanding', 'Memahami konsep-konsep abstrak dengan mendalam dan menyeluruh.'),
	(41, 'Abstract Concept Application', 'Menerapkan konsep-konsep abstrak dalam situasi dan konteks yang berbeda.'),
	(41, 'Identify Pattern & Relationship', 'Mengidentifikasi hubungan dan pola antara konsep-konsep abstrak.'),
	(41, 'Abstract Concept Classification', 'Mengklasifikasikan dan mengorganisir konsep-konsep abstrak secara logis dan sistematis.'),
	(41, 'Conceptual Application', 'Menghubungkan konsep-konsep abstrak dengan fenomena atau permasalahan dunia nyata.'),

	(42, 'Applying Learned Concepts', 'Menggunakan konsep-konsep yang dipahami dalam situasi yang relevan dan berbeda.'),
	(42, 'Identify Applied Concepts', 'Mengidentifikasi aplikasi konsep-konsep abstrak dalam solusi nyata.'),
	(42, 'Tailoring Abstract Concepts', 'Menyesuaikan konsep-konsep abstrak dengan kebutuhan dan konteks spesifik.'),
	(42, 'Integrate Abstract Concepts', 'Mengintegrasikan konsep-konsep abstrak dalam pemecahan masalah dan pengambilan keputusan.'),
	(42, 'Applying Abstract Concept for Innovation', 'Menciptakan solusi yang efektif dan inovatif dengan menerapkan konsep-konsep abstrak.'),

	(43, 'Problem Identification', 'Identifikasi masalah, mengenali dan mendefinisikan masalah adalah langkah pertama dalam proses pemecahan masalah, melibatkan pemahaman yang baik tentang Situasi dan Kemampuan untuk mengajukan pertanyaan yang tepat.'),
	(43, 'Problem Analysis', 'Menganalisis masalah tersebut, melibatkan pemahaman tentang penyebab masalah, dan mencari tahu semua faktor yang berkontribusi pada masalah tersebut.'),
	(43, 'Hypotheses & Finding Solutions', 'Pembuatan hipotesis dan pencarian solusi yang menghasilkan berbagai alternatif solusi untuk masalah tersebut, dan mengevaluasi masing-masing solusi tersebut berdasarkan kelayakan dan potensi dampaknya.'),
	(43, 'Implement Solution', 'Mengimplementasikan solusi melibatkan perencanaan, pengorganisasian sumber daya, dan pengelolaan perubahan.'),
	(43, 'Evaluation', 'Mengevaluasi hasil setelah solusi diimplementasikan, jika solusi tidak mengatasi masalah, mungkin perlu kembali ke langkah sebelumnya dan mencoba solusi lain.'),

	(44, 'Observe & Identify', 'Mengamati dan mengidentifikasi adanya masalah yang muncul.'),
	(44, 'Define Problem', 'Mendefinisikan dengan jelas masalah yang dihadapi.'),
	(44, 'Define Cause/Effect', 'Mengidentifikasi penyebab utama dari masalah tersebut.'),
	(44, 'Indepth Analysis', 'Mengumpulkan informasi yang relevan untuk memahami masalah secara mendalam.'),
	(44, 'Problem Statement', 'Menyusun pernyataan masalah yang jelas dan terukur.'),

	(45, 'Analyse Pattern & Trend', 'Menganalisis tren atau pola yang dapat menyebabkan munculnya masalah di masa depan.'),
	(45, 'Involve Others', 'Melibatkan anggota tim atau pemangku kepentingan terkait dalam proses identifikasi potensi masalah.'),
	(45, 'Predictive Insight', 'Menggunakan pengetahuan dan pengalaman sebelumnya untuk mengantisipasi masalah yang mungkin terjadi.'),
	(45, 'Scenario Development', 'Membuat skenario atau simulasi untuk memperkirakan kemungkinan masalah di masa depan.'),
	(45, 'Mitigation Plans', 'Mengembangkan rencana pencegahan atau mitigasi untuk mengurangi dampak masalah yang diantisipasi.'),

	(46, 'Systematic Analysis', 'Menganalisis masalah secara sistematis dengan menggunakan metode yang tepat.'),
	(46, 'Relevant Data Collection', 'Mengumpulkan data dan informasi yang relevan untuk memahami akar penyebab masalah.'),
	(46, 'Identify Contribution Factors', 'Mengidentifikasi faktor-faktor yang berkontribusi terhadap masalah.'),
	(46, 'Appropriate Analytical Tools', 'Menggunakan alat analisis yang sesuai, seperti diagram sebab-akibat atau analisis pareto.'),
	(46, 'Indepth Issues Understanding', 'Membuat pemahaman yang mendalam tentang masalah untuk mencari solusi yang tepat.'),

	(47, 'Risk Potential Identification', 'Identifikasi potensi yang dapat membahayakan atau mengganggu operasi atau tujuan organisasi.'),
	(47, 'Risk Level Analysis', 'Analisis tingkat keparahan dan kemungkinan terjadinya risiko.'),
	(47, 'Risk Evaluation', 'Evaluasi risiko dengan membandingkan tingkat risiko dengan kriteria yang telah ditetapkan atau toleransi risiko organisasi. '),
	(47, 'Risk Mitigation', 'Mitigasi risiko dengan mengembangkan dan menerapkan strategi untuk mengurangi dampak atau kemungkinan terjadinya risiko.'),
	(47, 'Risk Monitoring', 'Monitoring risiko dengan secara teratur meninjau dan melaporkan status risiko dan efektivitas strategi mitigasi risiko.'),

	(48, 'Strength', 'Mengidentifikasi kekuatan (strengths) organisasi yang memberikan keunggulan kompetitif.'),
	(48, 'Weakness', 'Mengenali kelemahan (weaknesses) organisasi yang perlu diperbaiki atau diatasi.'),
	(48, 'Opportunities', 'Mengidentifikasi peluang (opportunities) di lingkungan eksternal yang dapat dimanfaatkan.'),
	(48, 'Threats', 'Menganalisis ancaman (threats) di lingkungan eksternal yang dapat mempengaruhi kinerja organisasi.'),
	(48, 'SWOT v.s Goal Analysis', 'Menghubungkan temuan analisis SWOT dengan tujuan ataupun pengambilan keputusan strategis.'),

	(49, 'Politics', 'Menganalisis faktor-faktor politik yang dapat mempengaruhi organisasi.'),
	(49, 'Economy', 'Menganalisis faktor-faktor ekonomi yang dapat mempengaruhi kinerja organisasi.'),
	(49, 'Social', 'Menganalisis faktor-faktor sosial yang dapat memengaruhi preferensi dan perilaku konsumen.'),
	(49, 'Technology', 'Menganalisis faktor-faktor teknologi yang dapat mempengaruhi inovasi dan efisiensi organisasi.'),
	(49, 'Environment & Legal', 'Menganalisis faktor-faktor lingkungan dan hukum yang dapat memengaruhi keberlanjutan operasional organisasi.'),

	(50, 'Analyse & Evaluate', ' Analisis dan evaluasi informasi dari berbagai sumber, menganalisis informasi tersebut, dan mengevaluasi relevansinya dan kualitasnya untuk keputusan yang akan diambil.'),
	(50, 'Manage Risk', 'Pemahaman dan mempertimbangkan risiko dan konsekuensi dari berbagai pilihan tindakan.'),
	(50, 'Objective-Intuition Balance', 'Memanfaatkan intuisi terutama ketika menghadapi situasi yang kompleks atau ambigu.'),
	(50, 'Compliance with Objectives', 'Memastikan kesesuaian dengan tujuan, keputusan yang diambil sejalan dengan tujuan dan strategi organisasi.'),
	(50, 'Creative', 'Kreativitas dalam mencari alternatif dan mengambil keputusan yang paling sesuai.'),

	(51, 'Analyse & Evaluate', 'Menganalisis dan mengevaluasi berbagai alternatif berdasarkan data dan informasi yang ada.'),
	(51, 'Pro-Cons Analysis', 'Mengidentifikasi kelebihan dan kekurangan masing-masing alternatif.'),
	(51, 'Risk Analysis', 'Mengukur risiko dan dampak dari setiap alternatif yang dipertimbangkan.'),
	(51, 'Key Factors Analysis', 'Mempertimbangkan faktor-faktor kunci dalam pengambilan keputusan, seperti biaya, keuntungan, dan konsistensi dengan tujuan organisasi.'),
	(51, 'Evidence Based Decision', 'Memilih alternatif terbaik berdasarkan bukti yang ada serta analisis yang obyektif.'),

	(52, 'Idea Generation', 'Mengembangkan dan menciptakan berbagai ide dan konsep baru, mempertimbangkan berbagai kemungkinan dan pendekatan, bukan hanya mengikuti cara yang sudah ada.'),
	(52, 'Intellectual Risk', 'Mengeksplorasi ide-ide yang tidak biasa atau tidak konvensional dan bersedia mengambil risiko intelektual.'),
	(52, 'Unique Solution', 'Menemukan solusi unik dan inovatif untuk masalah, melihat masalah dari berbagai perspektif dan merumuskan jawaban yang tidak terduga.'),
	(52, 'Mental Flexibility', 'Berubah dan beradaptasi dalam memikirkan ide dan pendekatan, melibatkan keterbukaan terhadap perubahan dan kemampuan untuk memikirkan di luar batas tradisional.'),
	(52, 'Collaborative', 'Bekerja dengan orang lain untuk mengembangkan dan memperkaya ide, melibatkan keterampilan seperti mendengarkan, memberikan dan menerima umpan balik, dan membangun pada ide orang lain.'),
	(53, 'Built-in', 'TBD'),

	(54, 'Idea Generation', 'Menghasilkan ide-ide baru dan orisinal, tidak hanya mempertimbangkan cara kerja saat ini, tetapi juga mencari pendekatan baru yang dapat meningkatkan hasil.'),
	(54, 'Problem Solution', 'penggunaan pengetahuan dan keterampilan untuk mencari solusi baru bagi masalah yang ada, mencakup perubahan proses yang ada, atau menciptakan solusi yang sepenuhnya baru.'),
	(54, 'Continuous Learning', 'memiliki keinginan untuk belajar dan mengembangkan pemahaman mereka. Mereka mencari pengetahuan baru dan terus mencari cara untuk meningkatkan dan inovasi.'),
	(54, 'Failure Risk', 'Menghadapi dan mengelola risiko, dan tidak takut gagal.'),
	(54, 'Collaborative', 'kerja sama dengan orang lain untuk menghasilkan ide dan solusi, melibatkan berbagi pengetahuan dan sumber daya, dan bekerja sama untuk mencapai tujuan bersama.'),

	(55, 'Different Perspectives', 'Mampu melihat masalah atau situasi dari sudut pandang yang berbeda dan mencari solusi yang tidak konvensional atau inovatif.'),
	(55, 'Taking Risks', 'Berani mengambil risiko dan mencoba pendekatan yang tidak biasa.'),
	(55, 'Unexpected Ideas', 'Menggabungkan ide-ide yang tidak terduga atau tidak terkait untuk menghasilkan solusi kreatif.'),
	(55, 'Strong Imagination', 'Memiliki imajinasi yang kuat dan kemampuan berpikir asosiatif.'),
	(55, 'Challenging the Status Quo', 'Mengatasi batasan pemikiran yang konvensional dan menantang status quo.'),

	(56, 'Generating New Ideas', 'Mampu menghasilkan sejumlah ide baru, unik, dan bervariasi dalam menghadapi masalah atau tantangan.'),
	(56, 'Divergent Thinking', 'Pemikiran yang menghasilkan beragam alternatif dan opsi.'),
	(56, 'Creative Techniques', 'Menggunakan teknik kreatif seperti random stimulus atau analogi untuk memicu proses ideasi.'),
	(56, 'Rapid Idea Development', 'Kemampuan mengembangkan ide yang cepat dan produktif.'),
	(56, 'Ideation and Evaluation', 'Memisahkan proses ideasi dari proses penilaian atau kritik.'),

	(57, 'Unrelated Connections', 'Mampu menghubungkan ide-ide yang tampaknya tidak terkait untuk menghasilkan ide-ide baru dan kreatif.'),
	(57, 'Free Association', 'Melakukan asosiasi bebas dan menggabungkan konsep yang berbeda.'),
	(57, 'Rapid and Flexible Association', 'Memiliki kemampuan asosiasi yang cepat dan fleksibel.'),
	(57, 'Cross-Disciplinary', 'Berpikir lintas disiplin dan memanfaatkan pengetahuan dari berbagai bidang.'),
	(57, 'Creative Techniques', 'Menggunakan teknik seperti mind mapping atau brainstorming untuk menghasilkan ide-ide baru.'),

	(58, 'Critical Thinking', 'Kemampuan untuk menganalisis informasi dan situasi secara objektif, mengevaluasi argumen, mengidentifikasi asumsi, dan membuat keputusan yang didasarkan pada bukti dan logika yang valid. '),
	(58, 'Systems Thinking', 'Memahami bagaimana bagian dari sebuah sistem berinteraksi satu sama lain, melihat gambaran besar dan memahami saling ketergantungan dan interaksi di antara komponen-komponen sistem tersebut.'),
	(58, 'Future Analysis', 'Kemampuan untuk membuat perkiraan tentang perkembangan masa depan berdasarkan analisis tren dan pemahaman tentang lingkungan bisnis. '),
	(58, 'Visioning ', 'Kemampuan membayangkan kondisi masa depan yang diinginkan dan mengembangkan visi yang jelas dan menarik yang dapat membimbing pengambilan keputusan dan menginspirasi orang lain untuk bertindak.'),
	(58, 'Decision Making', 'Menganalisis situasi dan data yang kompleks, mengidentifikasi isu dan tren utama, dan membuat keputusan yang sejalan dengan tujuan dan visi strategis mereka.'),
	(59, 'Built-in', 'TBD'),

	(60, 'Projections', 'Membuat proyeksi tentang perkembangan masa depan berdasarkan tren yang diidentifikasi.'),
	(60, 'Historical Analysis', 'Menggunakan data historis dan tren saat ini untuk memperkirakan perubahan yang mungkin terjadi.'),
	(60, 'Scenario Analysis', 'Menggunakan teknik pemodelan atau simulasi untuk mengembangkan skenario masa depan yang berbeda.'),
	(60, 'Stakeholder Involvement', 'Melibatkan pemangku kepentingan terkait dalam proses perencanaan dan proyeksi masa depan.'),
	(60, 'Future Potential', 'Menyusun pemahaman yang komprehensif tentang potensi masa depan organisasi.'),

	(61, 'Environmental Scanning', 'Pemantauan dan analisis lingkungan eksternal organisasi untuk mengidentifikasi tren, perubahan, dan peluang atau ancaman potensial.'),
	(61, 'Internal Analysis', 'Penilaian lingkungan internal organisasi, termasuk sumber daya, kemampuan, kekuatan, dan kelemahan. '),
	(61, 'Competitor Analysis', 'Analisis pesaing dalam hal strategi, kekuatan, kelemahan, produk, dan posisi pasar mereka. '),
	(61, 'Risk Analysis', 'Identifikasi risiko dan ketidakpastian potensial yang bisa mempengaruhi tujuan strategis organisasi.'),
	(61, 'Decision Making', 'Membuat keputusan yang sejalan dengan tujuan analisa strategis.'),

	(62, 'Identify Pattern & Relations', 'Mengidentifikasi pola dan hubungan antara bagian-bagian dari sistem dan memahami bagaimana perubahan pada satu bagian dapat mempengaruhi bagian lainnya.'),
	(62, 'Seeing "Big Picture"', 'Mampu melihat "gambaran besar" dan memahami tujuan dan fungsi keseluruhan dari sistem adalah aspek penting dari berpikir sistemik.'),
	(62, 'Longterm Analysis', 'Pertimbangan tentang dampak jangka panjang dari tindakan atau perubahan, bukan hanya hasil jangka pendek.'),
	(62, 'Complexity', 'Kemampuan untuk toleran dan paham tentang isu dan dinamika yang komplek. '),
	(62, 'Systemic Change', 'Mampu merancang dan menerapkan perubahan yang berdampak pada sistem secara keseluruhan, bukan hanya bagian individu.'),

	(63, 'Vision Development', 'Kemampuan untuk menciptakan visi jangka panjang yang inspiratif dan memotivasi orang lain.'),
	(63, 'Clear & Concise', 'Kejelasan dalam menggambarkan visi dengan kata-kata yang sederhana dan kuat.'),
	(63, 'Vision v.s Values', 'Kemampuan untuk mengaitkan visi dengan nilai-nilai inti organisasi.'),
	(63, 'Visualization', 'Kreativitas dalam memvisualisasikan dan mengkomunikasikan visi kepada orang lain.'),
	(63, 'Vision Adjustment', 'Keahlian dalam mengidentifikasi peluang baru yang sesuai dengan visi yang ditetapkan.'),

	(64, 'Indepth Understanding', 'pemahaman yang kuat tentang data dan bagaimana menginterpretasikannya, membaca dan menganalisis data dalam berbagai format, termasuk grafik, diagram, dan tabel.'),
	(64, 'Identify Pattern & Trend', 'Mengidentifikasi pola dalam data sepanjang waktu dan mengidentifikasi tren berkelanjutan atau perubahan dalam pola tersebut.'),
	(64, 'Predicting', 'membuat prediksi tentang bagaimana tren ini mungkin berlanjut ke depan, dan apa dampaknya terhadap organisasi atau situasi.'),
	(64, 'Contextual Understanding', 'pengetahuan tentang konteks di mana data dikumpulkan dan tren sedang dianalisis juga penting; mencakup pemahaman tentang faktor-faktor ekonomi, sosial, teknologi, atau politik yang mungkin mempengaruhi tren.'),
	(64, 'Effective Communication', 'Menyampaikan temuan dan wawasan dengan cara yang jelas dan mudah dimengerti, melibatkan pembuatan laporan atau presentasi, atau menjelaskan temuan secara verbal.'),

	(65, 'Reliability/Kehandalan', 'Kemampuan untuk dapat diandalkan dalam menjalankan tanggung jawabnya, yang selalu diselesaikan dengan baik.'),
	(65, 'Honesty', 'Kemampuan untuk berbicara dengan jujur dan tidak menipu atau menyembunyikan fakta, transparan, dan menghindari praktik-praktik yang tidak etis.'),
	(65, 'Work Ethics', 'Mengadopsi dan berpegang pada prinsip/standar etika kerja yang tinggi, seperti menghargai kerahasiaan, menghindari konflik kepentingan, dan menjaga privasi orang lain.'),
	(65, 'Accountability', 'Menerima konsekuensi dari tindakan mereka dan mengambil tanggung jawab atas kesalahan atau kegagalan, tidak mencari kambing hitam atau menghindari tanggung jawab.'),
	(65, 'Consistency', 'Menunjukkan konsistensi antara kata dan tindakan, mempertahankan prinsip dan nilai yang konsisten dalam berbagai situasi, tidak mengorbankan prinsip demi keuntungan pribadi.'),

	(66, 'Take Responsibility', 'Mengambil tanggung jawab pribadi atas tindakan, keputusan, dan hasil kerja, dan bertanggung jawab atas keberhasilan dan kegagalan mereka.'),
	(66, 'Reliability', 'Bisa diandalkan dan dipercaya dalam memenuhi komitmen dan tenggat waktu, konsisten memenuhi janji mereka.'),
	(66, 'Transparency', 'Bersikap terbuka dan transparan dalam komunikasi, berbagi informasi, dan memberikan pembaruan tentang kemajuan, proaktif menjaga para pemangku kepentingan tetap terlibat.'),
	(66, 'Solution Provider', 'Mengambil inisiatif untuk mengatasi tantangan dan menemukan solusi ketika menghadapi hambatan atau kegagalan.'),
	(66, 'Continuous Improvement', 'Mengadopsi pola pikir pertumbuhan dan mencari peluang pengembangan pribadi dan profesional, berkomitmen untuk belajar dari pengalaman mereka dan terus meningkatkan keterampilan dan kinerja mereka.'),

	(67, 'Understanding Ethics', 'Memahami nilai-nilai etika yang berlaku dalam organisasi, profesi, atau masyarakat.'),
	(67, 'Understanding Ethical Norms & Standards', 'Mengenali dan memahami norma dan standar yang berlaku dalam konteks etika.'),
	(67, 'Identifiy Ethical Dilemmas', 'Menyadari dan mengidentifikasi dilema etika dalam situasi yang kompleks, mengenali konflik moral dan nilai-nilai yang bertentangan.'),
	(67, 'Ethical Implications', 'Mampu mengidentifikasi implikasi etika dari keputusan dan tindakan yang diambil,mempertimbangkan konsekuensi etis dari tindakan.'),
	(67, 'Ethics v.s Integrity', 'Memahami pentingnya etika dalam menjaga kepercayaan dan integritas.'),

	(68, 'Honest', 'Bersikap jujur dan terbuka dalam semua tindakan dan komunikasi.'),
	(68, 'Transparent', 'Transparan dalam melibatkan orang lain dalam proses pengambilan keputusan.'),
	(68, 'Consistency', 'Membangun kepercayaan dengan menjadi konsisten dalam komunikasi yang jujur dan transparan.'),
	(68, 'Open Communication', 'Kemampuan untuk menyampaikan informasi yang jujur dan akurat tanpa menyembunyikan fakta penting.'),
	(68, 'Ethical', 'Menghindari konflik kepentingan dan praktik yang tidak etis.'),

	(69, 'Personal v.s Organization', 'Keselarasan nilai-nilai pribadi dengan nilai-nilai organisasi.'),
	(69, 'Vision Ownership', 'Pemahaman yang kuat terhadap visi, misi, dan tujuan organisasi.'),
	(69, 'Adaptability', 'Kemampuan untuk beradaptasi dengan perubahan dan arah strategis organisasi.'),
	(69, 'Behavior vs. Value', 'Konsistensi antara tindakan dan nilai-nilai organisasi.'),
	(69, 'Commitment', 'Komitmen untuk berkontribusi secara aktif dalam mencapai tujuan organisasi.'),

	(70, 'Adherence', 'Berpegang teguh pada prinsip-prinsip etika dan integritas dalam semua situasi.'),
	(70, 'Courage', 'Menunjukkan keberanian dan integritas dalam menghadapi situasi yang menantang.'),
	(70, 'Resilience & Resistance', 'Mampu mempertahankan standar etika yang tinggi bahkan dalam tekanan atau godaan.'),
	(70, 'Consistency', 'Konsisten dalam menjalankan prinsip-prinsip etika dalam kehidupan sehari-hari.'),
	(70, 'Respect', 'Menghormati kode etik atau standar profesi yang berlaku.'),

	(71, 'Environmental Awareness', 'Memiliki kesadaran terhadap lingkungan dan dampak dari aktivitas bisnis.'),
	(71, 'Taking Action', 'Mengambil langkah-langkah untuk menjaga dan melindungi lingkungan.'),
	(71, 'Adopt Sustainable Concept', 'Mengadopsi praktik bisnis yang ramah lingkungan dan berkelanjutan.'),
	(71, 'Minimize Carbon Footprint', 'Meminimalkan jejak karbon dan mengurangi penggunaan sumber daya alam yang tidak terbarukan.'),
	(71, 'Promote Sustainability', 'Mendorong inisiatif atau kebijakan yang berkontribusi pada keberlanjutan lingkungan.'),

	(72, 'Social Impact Acumen', 'Memahami dampak sosial dari tindakan dan keputusan yang diambil.'),
	(72, 'Commit to Contribute', 'Berkomitmen untuk berkontribusi pada kesejahteraan sosial dan pembangunan yang berkelanjutan.'),
	(72, 'Community Driven', 'Memperhatikan kepentingan masyarakat dan memperjuangkan keadilan sosial.'),
	(72, 'Voluntary Engagement', 'Melibatkan diri dalam kegiatan sosial atau sukarela untuk memberi manfaat kepada komunitas.'),
	(72, 'Social Impact Consideration', 'Mempertimbangkan dampak sosial dalam pengambilan keputusan bisnis atau organisasi.'),

	(73, 'Verbal and Written Expression', 'Kemampuan untuk dengan jelas menyampaikan ide dan informasi, baik secara lisan maupun tertulis, melibatkan pemilihan kata dan frase yang tepat, serta penggunaan tata bahasa dan tanda baca yang benar.'),
	(73, 'Listening', 'Komunikasi bukan hanya tentang berbicara; itu juga melibatkan mendengarkan dan memahami pesan orang lain, melibatkan kemampuan untuk memahami dan menafsirkan informasi yang disampaikan oleh orang lain dan memberikan umpan balik yang konstruktif.'),
	(73, 'Non-verbal Communication', 'Memahami tentang bagaimana gerakan tubuh, kontak mata, dan ekspresi wajah dapat mempengaruhi komunikasi, melibatkan pemahaman tentang bagaimana nada suara dan infleksi dapat mempengaruhi makna pesan.'),
	(73, 'Presentation Skills', 'Kemampuan menyampaikan informasi atau ide kepada audiens, baik secara lisan maupun melalui media visual.'),
	(73, 'Interpersonal Skills', 'Kemampuan untuk berinteraksi dengan orang lain dengan cara yang sopan dan menghargai, mengenali norma-norma sosial dan budaya, dan mampu beradaptasi gaya komunikasi untuk memenuhi kebutuhan dan harapan orang lain.'),
	(74, 'Built-in', 'TBD'),

	(75, 'Clear, Concise & Compelling', 'Menyampaikan temuan dan wawasan yang diperoleh dari visualisasi data secara jelas, ringkas, dan persuasif.'),
	(75, 'Clarity', 'Menggunakan bahasa yang mudah dipahami oleh audiens yang dituju.'),
	(75, 'Audience Centric', 'Menyesuaikan presentasi dengan kepentingan dan latar belakang audiens.'),
	(75, 'Illustrative', 'Menggunakan contoh dan ilustrasi yang relevan untuk menggambarkan dan menjelaskan temuan.'),
	(75, 'Insight Data Driven', 'Mengkomunikasikan implikasi dan rekomendasi berdasarkan temuan visualisasi data yang disajikan.'),

	(76, 'Clear, Concise & Compelling', 'Kemampuan untuk menyampaikan visi dan strategi dengan cara yang jelas, persuasif, dan inspiratif.'),
	(76, 'Audience Adaptability', 'Keahlian dalam berkomunikasi dengan berbagai jenis audiens dan memahami kebutuhan komunikasi mereka.'),
	(76, 'Motivation/Vision Interoperability', 'Kemampuan untuk menginspirasi dan memotivasi orang lain agar mereka dapat terhubung dengan visi dan berkontribusi untuk mencapainya.'),
	(76, 'Provoke Storytelling', 'Keterampilan dalam menggunakan cerita dan contoh yang relevan untuk mendukung komunikasi visi dan strategi.'),
	(76, 'Active Listening', ' Kemampuan mendengarkan aktif dan mengatasi hambatan komunikasi untuk memastikan pemahaman yang baik.'),

	(77, 'Sharing', 'Berbagi informasi yang relevan, akurat, dan berguna dengan anggota jaringan Anda.'),
	(77, 'Clear & Concise', 'Menyampaikan pesan dengan cara yang jelas dan mudah dipahami.'),
	(77, 'Information Processing', 'Menerima dan memproses informasi dari anggota jaringan dengan teliti.'),
	(77, 'Communication Tools', 'Menggunakan alat komunikasi yang efektif, seperti email, telepon, atau media sosial, untuk pertukaran informasi.'),
	(77, 'Building Comm. Chanel', 'Membangun saluran komunikasi yang efisien dan terbuka untuk mempermudah pertukaran informasi.'),

	(78, 'Verbal Articulation', 'Mengungkapkan gagasan secara jelas dan terstruktur dalam komunikasi lisan.'),
	(78, 'Persuasive Speaking', 'Menggunakan gaya berbicara yang meyakinkan dan mempengaruhi pendengar.'),
	(78, 'Adaptive Language & Tone', 'Menyesuaikan bahasa dan tone yang sesuai dengan audiens yang dituju.'),
	(78, 'Adaptive Body Language', 'Menggunakan bahasa tubuh yang mendukung pesan yang disampaikan.'),
	(78, 'Manage Anxiety', 'Mengelola kecemasan dan ketegangan saat berbicara di depan umum.'),

	(79, 'Prompt Response', 'Memberikan tanggapan yang relevan, berbobot, dan tepat waktu terhadap komunikasi dari orang lain.'),
	(79, 'Active Listening', 'Mendengarkan dengan cermat dan memahami isi pesan sebelum memberikan tanggapan.'),
	(79, 'Articulating Opinions', 'Menyampaikan pendapat atau ide dengan cara yang jelas dan terstruktur.'),
	(79, 'Receiving Feedback', 'Menerima umpan balik dengan terbuka dan merespons secara konstruktif.'),
	(79, 'Adaptive Style & Tone', 'Menyesuaikan gaya dan tone tanggapan dengan situasi dan audiens yang dituju.'),

	(80, 'Adaptive Communication Style', 'Kemampuan untuk mengadaptasi gaya komunikasi sesuai dengan konteks dan audiens yang berbeda.'),
	(80, 'Clear & Concise', 'Keahlian dalam menyampaikan informasi dengan jelas, terstruktur, dan mudah dipahami.'),
	(80, 'Active Listening', 'Kemampuan untuk mendengarkan aktif dan memahami perspektif orang lain.'),
	(80, 'Empathic Response', 'Keterampilan dalam menyampaikan respon ataupun umpan balik secara efektif dan konstruktif.'),
	(80, 'Persuasive Communication', 'Kemampuan untuk menjelaskan maksud, ide, tujuan kepada orang lain dengan persuasif.'),

	(81, 'Focused', 'Memberikan perhatian penuh kepada pembicara dan memfokuskan diri pada pesan yang disampaikan.'),
	(81, 'Avoid Distractions', 'Menghindari gangguan dan interupsi saat orang lain berbicara.'),
	(81, 'Active Confirmation', 'Mengajukan pertanyaan yang relevan dan mengonfirmasi pemahaman saat mendengarkan.'),
	(81, 'Interest & Empathy', 'Menunjukkan minat dan empati melalui bahasa tubuh dan ekspresi wajah.'),
	(81, 'Summarize', 'Mencatat atau merangkum informasi penting saat mendengarkan.'),

	(82, 'Clear & Organized', 'Menyampaikan ide dan informasi secara efektif melalui tulisan yang jelas dan teratur.'),
	(82, 'Appropriate Style', 'Menggunakan gaya penulisan yang sesuai dengan tujuan dan audiens yang dituju.'),
	(82, 'Logical Structure', 'Mengorganisir dan menyusun konten dengan struktur yang logis dan koheren.'),
	(82, 'Grammar & Writing Conventions', 'Memperhatikan tata bahasa, ejaan, dan tanda baca yang tepat dalam tulisan.'),
	(82, 'Editing & Revising', 'Mengedit dan merevisi tulisan untuk meningkatkan kejelasan dan ketepatan.'),

	(83, 'Relationship Building', 'Kemampuan untuk membangun dan mempertahankan hubungan yang kuat dan positif dengan berbagai orang, mencakup rekan kerja, sejawat, atasan, klien, dan bahkan pesaing.'),
	(83, 'Communication', ' Komunikasi efektif melibatkan berbicara dengan jelas, percaya diri,  aktif mendegarkan dan memahami perspektif orang lain.'),
	(83, 'Reciprocity', 'Kemampuan timbal balik memberi serta menerima dan menawarkan bantuan, saran, atau sumber daya, dalam rangka keuntungan bersama'),
	(83, 'Social Mapping', 'Kemampuan memahami dinamika interaksi sosial dan mampu bernavigasi dengan cekatan, tahu kapan harus berbicara,  mendengarkan, dan berinteraksi dalam konteks yang berbeda secara tepat.'),
	(83, 'Opportunity Identification', 'Kemampuan melihat dan menciptakan peluang untuk kolaborasi, kemitraan, atau kemajuan bersama.'),
	(84, 'Built-in', 'TBD'),

	(85, 'Showing Interest', 'Menunjukkan minat dan perhatian terhadap individu dan kelompok dalam konteks profesional.'),
	(85, 'Building Trust', 'Membangun saling percaya dan kepercayaan melalui interaksi positif dan saling membantu.'),
	(85, 'Transparent Communication', 'Menjaga komunikasi yang terbuka dan transparan dalam hubungan profesional.'),
	(85, 'Appreciate Others', 'Menghargai kontribusi dan keberhasilan anggota jaringan profesional.'),
	(85, 'Supportive', 'Memberikan dukungan dan bantuan ketika diperlukan untuk memperkuat hubungan.'),

	(86, 'Perspective Mapping', 'Kemampuan untuk mengenali dan memahami perspektif, kebutuhan, dan motivasi orang lain.'),
	(86, 'Active Listening', 'Keterampilan dalam mendengarkan aktif dalam rangka memahami perspektif orang lain.'),
	(86, 'Inclusiveness', 'Kepekaan terhadap perbedaan individu dan keanekaragaman dalam tim atau organisasi.'),
	(86, 'Information Gathering', 'Kemampuan untuk menggali informasi yang relevan tentang orang lain dan menggunakan wawasan tersebut dalam pengaruh dan persuasi.'),
	(86, 'Common Ground', 'Kreativitas dalam mencari kesamaan atau titik persamaan dengan orang lain.'),
	(87, 'Built-in', 'TBD'),

	(88, 'Identify Situational Dynamics', 'Kemampuan untuk memahami dan mengevaluasi situasi yang sedang dihadapi, termasuk dinamika tim, lingkungan, dan tantangan.'),
	(88, 'Identify Situational Change', 'Kepekaan terhadap perubahan dan perkembangan dalam tim atau lingkungan kerja.'),
	(88, 'Analyse Relevant Information ', 'Keterampilan dalam mengumpulkan dan menganalisis informasi yang relevan.'),
	(88, 'Seeing "Big Picture"', 'Kemampuan untuk melihat keseluruhan gambaran dan menghubungkan situasi dengan tujuan yang ingin dicapai.'),
	(88, 'Anticipating', 'Kreativitas dalam mengantisipasi dan menghadapi hambatan atau tantangan yang mungkin muncul.'),

	(89, 'Collaborative', 'Kemampuan untuk bekerja dengan orang lain menuju tujuan bersama, membagi tugas dan tanggung jawab, dan mencapai hasil bersama.'),
	(89, 'Communication', 'Kemampuan menyampaikan ide dan informasi dengan jelas, mendengarkan dan memahami sudut pandang orang lain, dan membantu memfasilitasi diskusi dan negosiasi.'),
	(89, 'Peer Support', 'Saling mendukung dan membantu anggota tim lainnya, berbagi pengetahuan, sumber daya, memberi bantuan, dan berkontribusi pada lingkungan positif dan kolaboratif.'),
	(89, 'Trust & Respect', 'Saling menghargai dan mempercayai antara anggota tim, penghormatan pada perbedaan individu, kontribusi setiap orang, dan kepercayaan pada setiap anggota tim.'),
	(89, 'Conflict & Resolution', 'Kemampuan untuk mengenali, mengelola, dan menyelesaikan konflik dalam cara yang konstruktif dan profesional.'),
	(90, 'Built-in', 'TBD'),

	(91, 'Team Assessment', 'Kemampuan untuk mengenali kebutuhan, motivasi, kekuatan, dan kelemahan anggota tim.'),
	(91, 'Individual Differencies', 'Kepekaan terhadap perbedaan individu dan kontribusi unik yang dapat diberikan oleh masing-masing anggota tim.'),
	(91, 'Group Dynamics', 'Kepekaan terhadap dinamika kelompok dan hubungan antar anggota tim.'),
	(91, 'Individual v.s Team Interests', 'Kemampuan untuk memahami kebutuhan individu dan mempertimbangkan kepentingan kelompok.'),
	(91, 'Optimize Contribution', 'Kreativitas dalam merancang optimalisasi kontribusi anggota tim.'),

	(92, 'Identify Contributions', 'Kemampuan untuk mengakui dan menghargai prestasi, usaha, dan kontribusi positif yang dibuat oleh anggota tim atau individu.'),
	(92, 'Accomplishment v.s. Recognition', 'Kepekaan terhadap pencapaian individu dan penghargaian yang sesuai.'),
	(92, 'Showing Acknowledgement', 'Keterampilan dalam memberikan pengakuan secara terbuka dan dengan cara yang bermakna.'),
	(92, 'Appreciative Environment', 'Kemampuan untuk menciptakan lingkungan yang mendorong apresiasi dan penghargaan timbal balik.'),
	(92, 'Recognition Programs', 'Kreativitas dalam merancang program penghargaan yang memotivasi dan memberikan insentif bagi pengembangan individu.'),

	(93, 'Inclusiveness', 'Menegakkan prinsip-prinsip kesetaraan, memastikan bahwa setiap anggota tim diperlakukan secara adil dan setara.'),
	(93, 'Supportive Policies', 'Menerapkan kebijakan yang mendukung keberagaman dan mencegah diskriminasi di tempat kerja.'),
	(93, 'Freedom of Expression', 'Menghormati hak asasi manusia dan menghargai kebebasan berekspresi dalam konteks diversitas.'),
	(93, 'Inclusive Approach', 'Mengadopsi pendekatan yang inklusif dalam pengambilan keputusan dan pengelolaan sumber daya.'),
	(93, 'Monitoring & Evaluation', 'Melakukan evaluasi dan pengawasan berkala untuk memastikan kesetaraan dan keberagaman di dalam tim.'),

	(94, 'Recognition of Conflict', 'Kemampuan untuk mengidentifikasi konflik ketika mereka muncul. Ini melibatkan pengenalan tanda-tanda ketidaksepakatan atau ketegangan dan pemahaman tentang isu atau perbedaan yang mendasar yang menyebabkan konflik.'),
	(94, 'Communication', 'Keterampilan komunikasi yang baik sangat penting dalam penyelesaian konflik, active listening, fairness, inclusive.'),
	(94, 'Problem Solving', 'Mencari solusi atas perbedaan pendapat atau masalah yang menyebabkan konflik, melibatkan kreativitas, kritis, dan pemetaan perspektif.'),
	(94, 'Negotiation', 'Menjalankan negosiasi untuk penyelesaian konflik, pencarian kompromi atau kesepakatan yang dapat diterima semua pihak, sambil mempertahankan hubungan yang positif dan menghormati.'),
	(94, 'Emotional Intelligence', 'Kemampuan mengelola emosi dan merespons emosi orang lain, untuk meredakan ketegangan, membangun pemahaman, dan mendorong empati di antara pihak yang terlibat.'),

	(95, 'Recognize', 'Mengenali dan mengidentifikasi konflik yang muncul dalam tim atau antar individu dengan cepat dan tepat.'),
	(95, 'Objective Analysis', 'Meninjau secara objektif situasi yang memunculkan konflik dan mengidentifikasi pihak-pihak yang terlibat.'),
	(95, 'Empathic', 'Mendengarkan dengan empati dan memahami perspektif yang berbeda dari pihak yang terlibat dalam konflik.'),
	(95, 'Cause Effect Analysis', 'Mengidentifikasi sumber atau penyebab konflik secara akurat untuk mengarahkan penyelesaian yang tepat.'),
	(95, 'Anticipating Potential Conflict', 'Menggunakan keterampilan observasi dan analisis untuk mengenali tanda-tanda awal konflik yang mungkin muncul.'),

	(96, 'Openmind', 'Membuka pikiran untuk memahami dan menghargai perspektif yang berbeda dari individu dalam tim.'),
	(96, 'Respect & Tolerance', 'Menunjukkan toleransi dan penghormatan terhadap nilai-nilai, budaya, dan latar belakang yang berbeda dalam tim.'),
	(96, 'Knowledge & Experiences Exchange', 'Mendorong pertukaran pengetahuan dan pengalaman untuk memperkaya pemahaman dan perspektif tim.'),
	(96, 'Broadmind', 'Memperluas wawasan dan pemahaman tentang perbedaan individu melalui pendidikan dan pelatihan yang relevan.'),
	(96, 'Differencies v.s Opportunity', 'Menggunakan perbedaan sebagai sumber kekuatan dan keunggulan dalam mencapai tujuan tim.'),

	(97, 'Opinions, Belief & Values', 'Menunjukkan toleransi terhadap perbedaan pendapat, kepercayaan, dan nilai-nilai.'),
	(97, 'Inclusiveness', 'Menciptakan lingkungan yang saling menghargai dan inklusif.'),
	(97, 'Individual Rights', 'Menghormati hak setiap individu untuk memiliki perspektif yang unik.'),
	(97, 'Backgrounds & Approaches', 'Mampu bekerja sama dengan orang-orang yang memiliki latar belakang dan pendekatan yang berbeda.'),
	(97, 'Open Dialogue', 'Menggunakan dialog terbuka dan komunikasi yang efektif untuk mengatasi perbedaan.'),

	(98, 'Finding Common Ground', 'Mencari titik temu yang dapat diterima oleh semua pihak dalam negosiasi.'),
	(98, 'Options Development', 'Menjelaskan opsi kompromi dan mengidentifikasi manfaat serta konsekuensinya.'),
	(98, 'Setting Priorities', 'Menilai kepentingan relatif dan mengatur prioritas untuk merumuskan kompromi yang saling menguntungkan.'),
	(98, 'Setting Alternatives', 'Mempertimbangkan alternatif dan solusi kreatif untuk mencapai hasil yang memuaskan.'),
	(98, 'Persuassion', 'Mengomunikasikan kompromi dengan cara yang persuasif dan mengajak pihak lain untuk menerima.'),

	(99, 'Collaborative Atmosphere', 'Membangun atmosfer kerjasama dan mencari solusi yang menguntungkan semua pihak.'),
	(99, 'Mutual Based Agreement', 'Mengevaluasi dan memastikan bahwa kesepakatan mencerminkan kepentingan dan kebutuhan semua pihak yang terlibat.'),
	(99, 'Expose on Benefit', 'Mengkomunikasikan manfaat dan nilai dari kesepakatan yang saling menguntungkan.'),
	(99, 'Detail on Agreement', 'Menyusun kesepakatan secara tertulis dengan jelas dan memperhatikan detail penting.'),
	(99, 'Implement & Monitoring Agreement', 'Mengikuti dan melaksanakan kesepakatan dengan itikad baik dan memastikan kepatuhan dari semua pihak.'),

	(100, 'Decision Making', 'Membuat keputusan yang tepat dan tepat waktu, sering kali dalam situasi yang kompleks atau bawah tekanan.'),
	(100, 'Motivation', 'Memotivasi dan menginspirasi timnya untuk bekerja keras dan mencapai tujuan mereka.'),
	(100, 'Communication', 'Efektif mengkomunikasikan visi, tujuan, dan harapan.'),
	(100, 'Teamworking', 'Mengatur dan mengarahkan tim, menetapkan tujuan dan tugas, dan memastikan bahwa semua anggota tim berkontribusi secara efektif.'),
	(100, 'Development', 'Mengembangkan orang lain tidak hanya fokus pada pencapaian tujuan, tetapi juga pada pengembangan dan pertumbuhan individu dalam tim mereka, melibatkan mentoring, coaching, atau memberikan umpan balik konstruktif.'),

	(101, 'Persuasion Technique', 'Penguasaan berbagai teknik dan taktik persuasi, seperti storytelling, pembentukan kesepakatan, dan menunjukkan empati.'),
	(101, 'Real Demand Analysis', 'Keahlian dalam mengidentifikasi kebutuhan dan kepentingan orang lain untuk mengarahkan pendekatan persuasif.'),
	(101, 'Argumentation', 'Kemampuan untuk membangun argumen yang logis dan meyakinkan.'),
	(101, 'Persuasion Strategy', 'Kreativitas dalam memilih strategi persuasi yang sesuai dengan situasi dan audiens.'),
	(101, 'Resilience', 'Keterampilan dalam menghadapi penolakan atau hambatan dan menemukan solusi yang memenuhi kepentingan semua pihak.'),
	(102, 'Built-in', 'TBD'),

	(103, 'Inspiring & Motivating', 'Kemampuan untuk menginspirasi, memotivasi, dan membimbing orang lain dalam mencapai tujuan bersama melalui pengaruh dan persuasi.'),
	(103, 'Trust & Authority', 'Keterampilan dalam menggunakan wewenang dan kepercayaan untuk mempengaruhi orang lain secara positif.'),
	(103, 'Communication', 'Kemampuan dalam berkomunikasi secara efektif dan mengartikulasikan visi serta tujuan yang inspiratif.'),
	(103, 'Strategy', 'Kreativitas dalam mengembangkan strategi pengaruh yang menggerakkan orang lain.'),
	(103, 'Collaborative & Supportive Environment', 'Keahlian dalam membangun lingkungan kerja yang kolaboratif dan mendukung untuk mencapai tujuan bersama.'),

	(104, 'Situational', 'Kemampuan untuk menyesuaikan gaya kepemimpinan sesuai dengan situasi, karakteristik anggota tim, dan kebutuhan tugas atau proyek.'),
	(104, 'People Mapping', 'Kepekaan terhadap gaya dan preferensi kerja anggota tim.'),
	(104, 'Individual Driven on Motivation', 'Keterampilan dalam mengelola dan memotivasi anggota tim dengan cara yang sesuai.'),
	(104, 'Individual Driven on Task', 'Kemampuan untuk memilih pendekatan yang efektif dalam memberikan arahan dan delegasi.'),
	(104, 'Integrating Styles', 'Kreativitas dalam menggabungkan berbagai gaya kepemimpinan untuk mencapai tujuan yang diinginkan.'),

	(105, 'Building Relation', 'Kemampuan untuk membentuk hubungan yang kuat dan saling mendukung dengan orang lain.'),
	(105, 'Building Trust', 'Keterampilan dalam membangun kepercayaan dan menghormati kebutuhan orang lain.'),
	(105, 'Building Network', 'Kemampuan untuk membangun jaringan dan menjalin hubungan yang positif dalam tim atau organisasi.'),
	(105, 'Collaborative', 'Keahlian dalam kolaborasi dan bekerja sama dengan orang lain untuk mencapai tujuan bersama.'),
	(105, 'Building Support', 'Kreativitas dalam mencari kesempatan untuk membangun dukungan dan kepercayaan dari berbagai pihak.'),

	(106, 'Goal Setting', 'Menetapkan tujuan yang jelas dan realistis, baik untuk diri sendiri maupun untuk tim.'),
	(106, 'Planning', 'Membuat rencana atau jadwal yang detail untuk mencapai tujuan tersebut, termasuk penentuan dan prioritasi langkah-langkah yang harus diambil, pengaturan jadwal, dan alokasi sumber daya.'),
	(106, 'Organizing', 'Mengatur sumber daya (seperti waktu, uang, atau tenaga kerja) dengan cara yang paling efisien dan efektif.'),
	(106, 'Time Management', 'Mengelola waktu dengan efisien, baik untuk diri sendiri maupun untuk orang lain, dan untuk menyeimbangkan tuntutan yang saling bertentangan terhadap waktu.'),
	(106, 'Monitoring', 'memantau kemajuan terhadap tujuan dan membuat penyesuaian rencana atau pendekatan jika diperlukan.'),
	(107, 'Built-in', 'TBD'),
	(108, 'Built-in', 'TBD'),

	(109, 'Prioritizing', 'Menetapkan urutan prioritas yang jelas untuk menyelesaikan tugas berdasarkan pentingnya.'),
	(109, 'Key Activities', 'Mengidentifikasi tugas yang memiliki dampak langsung pada pencapaian tujuan strategis atau memenuhi kebutuhan kritis.'),
	(109, 'Setting Criteria', 'Menggunakan kriteria seperti deadline, konsekuensi, atau dampak untuk membantu dalam penentuan prioritas tugas.'),
	(109, 'Stakeholder Involvement', 'Melibatkan tim atau pemangku kepentingan terkait dalam proses penentuan prioritas tugas.'),
	(109, 'Adjustment', 'Mengelola dan memperbarui daftar prioritas tugas secara teratur berdasarkan perubahan kondisi atau kebutuhan.'),

	(110, 'Role & Responsibility', 'Mendefinisikan tugas dan tanggung jawab dengan jelas dan terperinci.'),
	(110, 'Order & Priority', 'Menetapkan urutan dan prioritas tugas yang tepat.'),
	(110, 'Task Allocation', 'Mengalokasikan tugas kepada anggota tim yang sesuai dengan kompetensi dan kapasitas mereka.'),
	(110, 'Coordinating', 'Mengkoordinasikan tugas antara anggota tim untuk memastikan kelancaran pelaksanaan.'),
	(110, 'Ensure Support & Delegation', 'Memastikan delegasi tanggung jawab yang efektif dan saling mendukung.'),

	(111, 'Detail Planning', 'Merumuskan rencana yang terperinci dengan langkah-langkah spesifik.'),
	(111, 'Resource Identification', 'Menentukan sumber daya yang diperlukan untuk setiap langkah rencana.'),
	(111, 'Risk Analysis', 'Mengidentifikasi risiko potensial dan mengembangkan strategi mitigasi.'),
	(111, 'Order & Priority', 'Menetapkan urutan kegiatan yang logis dan efisien.'),
	(111, 'Stakeholder Involvement', 'Melibatkan pemangku kepentingan terkait dalam pengembangan rencana.'),

	(112, 'Change Identification', 'Mengidentifikasi perubahan kondisi atau informasi baru yang mempengaruhi pelaksanaan rencana.'),
	(112, 'Performance Evaluation', 'Mengevaluasi kinerja saat ini dan membandingkannya dengan tujuan yang telah ditetapkan.'),
	(112, 'Adjustment', 'Mengadakan pembaruan dan revisi rencana yang sesuai dengan perubahan yang terjadi.'),
	(112, 'Stakeholders Involvement', 'Melibatkan pemangku kepentingan terkait dalam proses penyesuaian rencana.'),
	(112, 'Ensure Flexibility', 'Memastikan fleksibilitas dalam mengubah rencana untuk mencapai tujuan secara efektif.'),

	(113, 'Target Setting', 'Menetapkan target dan tujuan yang jelas dan dapat diukur untuk diri sendiri dan tim, dan memastikan bahwa semua orang memahami apa yang perlu dicapai.'),
	(113, 'Project Management', 'Perencanaan, pengorganisasian, dan pengelolaan sumber daya untuk mencapai tujuan yang spesifik, termasuk jadwal, pemantauan, dan penyesuaian rencana.'),
	(113, 'PDCA & PICA', 'Pemantauan terhadap proses dan hasil, pengecekan terhadap standar kinerja, target, dan penyesuaian tindakan jika diperlukan.'),
	(113, 'Empowerment', 'Mengarahkan eksekusi juga melibatkan mendorong dan mendukung anggota tim untuk mencapai target, melibatkan pelatihan, pembinaan, dan motivasi.'),
	(113, 'Responsibility', 'Mampu mengarahkan eksekusi dan bertanggung jawab atas hasil mereka dan bersedia membuat penyesuaian yang diperlukan untuk memastikan keberhasilan.'),

	(114, 'Resource Identification', 'Mengidentifikasi sumber daya yang diperlukan untuk menyelesaikan tugas atau proyek dengan efektif.'),
	(114, 'Resource Allocation', 'Mengalokasikan sumber daya secara proporsional sesuai dengan prioritas dan kebutuhan yang ada.'),
	(114, 'Resource Availability', 'Memastikan ketersediaan sumber daya yang cukup, seperti tenaga kerja, anggaran, dan peralatan, untuk menjalankan tugas dengan lancar.'),
	(114, 'Optimizing Resources', 'Mengoptimalkan penggunaan sumber daya dengan mengidentifikasi dan mengatasi potensi pemborosan atau ketidakseimbangan.'),
	(114, 'Monitoring Resources', 'Melakukan pemantauan terhadap penggunaan sumber daya dan melakukan penyesuaian jika diperlukan untuk memaksimalkan efisiensi.'),

	(115, 'Setting Standards', 'Mengidentifikasi standar kualitas yang harus dipenuhi dalam pelaksanaan tugas atau proyek.'),
	(115, 'Setting Procedures', 'Mengembangkan prosedur dan metode kontrol kualitas untuk memastikan kepatuhan terhadap standar yang ditetapkan.'),
	(115, 'Testing & Inspection', 'Melakukan pengujian atau pemeriksaan terhadap hasil kerja untuk memastikan kualitas yang diharapkan.'),
	(115, 'Stakeholder Involvement', 'Melibatkan anggota tim dalam pengawasan dan pengendalian kualitas untuk meminimalkan kesalahan atau cacat.'),
	(115, 'Corrective Actions', 'Mengambil tindakan perbaikan atau pengembangan jika terjadi penyimpangan dari standar kualitas.'),

	(116, 'Regular/Ongoing Monitoring', 'Melakukan pemantauan teratur terhadap kemajuan proyek atau tugas sesuai rencana yang telah ditetapkan.'),
	(116, 'Colect Relevant Data', 'Mengumpulkan data yang relevan untuk mengukur kemajuan dan pencapaian tujuan.'),
	(116, 'Monitoring Report', 'Menyusun laporan kemajuan yang jelas dan terstruktur.'),
	(116, 'Plan v.s Actual', 'Menganalisis perbedaan antara kemajuan aktual dan rencana awal.'),
	(116, 'Identify Obstacles', 'Mengidentifikasi kendala atau hambatan yang mungkin mempengaruhi kemajuan dan mengambil tindakan yang diperlukan.'),
	(117, 'Built-in', 'TBD'),

	(118, 'Indicators Setting', 'Menentukan indikator kinerja yang relevan dan dapat diukur sesuai dengan tujuan yang telah ditetapkan.'),
	(118, 'Paramaters Setting', 'Mengidentifikasi parameter atau metrik yang digunakan untuk mengukur pencapaian tujuan.'),
	(118, 'Target/Standard Setting', 'Menetapkan target atau standar yang realistis untuk setiap indikator kinerja.'),
	(118, 'Monitoring System', 'Menyusun sistem pemantauan yang efektif untuk mengumpulkan data yang diperlukan.'),
	(118, 'KPI Roadshow', 'Mengkomunikasikan indikator kinerja kepada anggota tim atau pemangku kepentingan terkait.'),

	(119, 'Delegating', 'Kemampuan untuk mendelegasikan tugas dan wewenang kepada anggota tim dengan cara yang efektif dan efisien.'),
	(119, 'Communication', 'Keahlian dalam mengkomunikasikan tujuan, harapan, dan batasan tugas kepada anggota tim.'),
	(119, 'Directing', 'Keterampilan dalam memberikan arahan yang jelas dan memastikan pemahaman yang sama.'),
	(119, 'Facilitating', 'Kemampuan untuk memfasilitasi keterlibatan anggota tim dalam proses pengambilan keputusan terkait tugas yang didelegasikan.'),
	(119, 'Providing', 'Memberikan kesempatan kepada anggota tim untuk mengembangkan keterampilan dan pengetahuan mereka melalui tugas yang didelegasikan.'),

	(120, 'Identify Deviations', 'Mengidentifikasi penyimpangan atau masalah yang muncul dalam pelaksanaan tugas atau proyek.'),
	(120, 'Root Cause Analysis', 'Menganalisis akar penyebab masalah dan mengidentifikasi solusi yang tepat.'),
	(120, 'Plan & Implement', 'Merencanakan dan melaksanakan tindakan korektif yang diperlukan untuk mengatasi masalah.'),
	(120, 'Monitor & Evaluate', 'Memantau dan mengevaluasi hasil dari tindakan korektif yang diimplementasikan.'),
	(120, 'Communication', 'Mengkomunikasikan tindakan korektif kepada anggota tim dan memastikan pemahaman dan penerapan yang tepat.'),

	(121, 'Motivating', 'Kemampuan untuk memberikan dukungan semangat/motivasi yang diperlukan kepada anggota tim saat menjalankan tugas yang telah didelegasikan.'),
	(121, 'Guidance & Provision', 'Keterampilan dalam memberikan bimbingan, saran, dan sumber daya yang diperlukan untuk menyelesaikan tugas.'),
	(121, 'Monitoring', 'Kemampuan untuk memantau kemajuan tugas dan memastikan kualitas hasil kerja.'),
	(121, 'Demand Analysis', 'Kepekaan terhadap kebutuhan dan tantangan individu saat menjalankan tugas.'),
	(121, 'Supportive Environment', 'Kreativitas dalam menciptakan lingkungan yang mendukung pertumbuhan dan keberhasilan anggota tim.'),

	(122, 'Self Assessment', ' Kemampuan untuk memahami diri sendiri secara mendalam, termasuk kekuatan, kelemahan, nilai-nilai, minat, dan tujuan pribadi.'),
	(122, 'Intrinsic Motivation', 'Kemampuan untuk membangkitkan motivasi dari dalam diri sendiri, memiliki dorongan yang kuat untuk tumbuh dan mengembangkan diri, dan mempertahankan komitmen terhadap tujuan pengembangan pribadi.'),
	(122, 'Goal Setting', 'Kemampuan untuk merumuskan tujuan yang spesifik, terukur, dapat dicapai, relevan, dan berbatasan waktu, yang berfokus pada pengembangan pribadi.'),
	(122, 'Self Learning', 'Kemampuan untuk mengidentifikasi dan menggunakan berbagai sumber belajar, seperti buku, kursus online, mentor, atau pengalaman praktis, untuk meningkatkan pengetahuan, keterampilan, dan kompetensi pribadi.'),
	(122, 'Self Reflection', 'Kemampuan untuk secara teratur merefleksikan pengalaman, belajar dari kesalahan, dan mengevaluasi perkembangan diri sendiri, dengan tujuan untuk terus tumbuh dan meningkatkan diri secara pribadi dan profesional.'),
	(123, 'Built-in', 'TBD'),

	(124, 'Skill Assessment', 'Menilai keterampilan, pengetahuan, dan kompetensi saat ini'),
	(124, 'Identify Development Area', 'Mengidentifikasi area yang memerlukan pengembangan atau perbaikan'),
	(124, 'Prioritizing', 'Menetapkan prioritas untuk pengembangan diri'),
	(124, 'Achievement v.s. Requirements', 'Membandingkan diri dengan standar atau persyaratan industri'),
	(124, 'Using Feeback', 'Menggunakan umpan balik dari orang lain untuk menginformasikan analisis kebutuhan pengembangan'),

	(125, 'Identify Potential', 'Kemampuan untuk mengenali potensi dan kekuatan individu dalam organisasi, termasuk keterampilan, pengetahuan, dan bakat yang dapat dikembangkan lebih lanjut.'),
	(125, 'Guidance & Counselling', 'Kemampuan untuk memberikan panduan, dukungan, dan umpan balik yang konstruktif kepada individu untuk membantu mereka mengembangkan keterampilan dan mencapai tujuan pengembangan mereka.'),
	(125, 'Skill Development', 'Kemampuan untuk merancang dan menyampaikan pelatihan atau program pengembangan keterampilan yang efektif, yang relevan dengan kebutuhan individu dan organisasi.'),
	(125, 'Encourage & Motivate', 'Kemampuan untuk mendorong dan memotivasi individu untuk menggali potensi mereka, mendorong pertumbuhan pribadi, dan mencapai tingkat performa yang lebih tinggi.'),
	(125, 'Learning Facilitation', 'Kemampuan untuk menciptakan lingkungan yang mendukung pembelajaran, memfasilitasi pertukaran pengetahuan dan pengalaman, dan menyediakan sumber daya yang diperlukan untuk pengembangan individu.'),

	(126, 'Objective  Evaluation', 'Kemampuan untuk secara objektif mengevaluasi kekuatan dan kelemahan individu dalam tim atau organisasi.'),
	(126, 'Development Potential', 'Kepekaan terhadap potensi pengembangan dan area yang memerlukan perhatian lebih.'),
	(126, 'Development Needs', 'Keterampilan dalam mengidentifikasi kebutuhan pembelajaran dan pengembangan yang spesifik untuk individu.'),
	(126, 'Big Picture Perspective', 'Kemampuan untuk melihat keseluruhan gambaran dan menghubungkan kebutuhan individu dengan tujuan bersama.'),
	(126, 'Creative', 'Kreativitas dalam merancang program pengembangan yang sesuai untuk memenuhi kebutuhan identifikasi.'),

	(127, 'Development Goals', 'Menetapkan tujuan jangka pendek dan jangka panjang untuk pengembangan diri'),
	(127, 'Development Strategy', 'Merumuskan strategi dan sumber daya yang diperlukan untuk mencapai tujuan'),
	(127, 'Realistic Planning', 'Membuat jadwal realistis untuk mencapai tujuan pengembangan'),
	(127, 'Career v.s. Personal Goals', 'Mengintegrasikan rencana pengembangan dengan tujuan karier dan pribadi'),
	(127, 'Adaptive Development Plans', 'Menyesuaikan rencana pengembangan berdasarkan perubahan kebutuhan atau situasi'),

	(128, 'Active & Consistent', 'Melaksanakan rencana pengembangan secara aktif dan konsisten'),
	(128, 'Leveraging Opprotunities', 'Memanfaatkan peluang pengembangan seperti pelatihan, pembelajaran mandiri, dan pengalaman kerja'),
	(128, 'Seeking Support', 'Mencari dukungan dari mentor, pelatih, atau rekan kerja'),
	(128, 'Commitment', 'Berkomitmen untuk menginvestasikan waktu dan usaha dalam proses pembelajaran'),
	(128, 'Monitoring & Adjusting', 'Memonitor dan menyesuaikan tindakan pengembangan sesuai dengan umpan balik dan hasil'),

	(129, 'Supportinve Environment', 'Kemampuan untuk menciptakan dan mempertahankan lingkungan yang mendukung pembelajaran, pertumbuhan, dan pengembangan bagi anggota tim atau individu.'),
	(129, 'Collaborative & Open', 'Keahlian dalam membangun budaya pembelajaran yang terbuka dan kolaboratif.'),
	(129, 'Relevant & Engaging', 'Keterampilan dalam merancang program pembelajaran dan pengembangan yang relevan dan menarik.'),
	(129, 'Collaborative Knowledge Exchange', 'Kemampuan untuk memfasilitasi kolaborasi dan pertukaran pengetahuan antar anggota tim.'),
	(129, 'Creative & Inclusive Learning', 'Kreativitas dalam menerapkan metode pembelajaran yang inklusif.'),

	(130, 'Open Dialogue', 'Kemampuan untuk memberikan umpan balik yang konstruktif, jujur, dan tepat waktu kepada anggota tim atau individu.'),
	(130, 'Clear & Concise', 'Keterampilan dalam mengkomunikasikan umpan balik dengan cara yang jelas dan berfokus pada peningkatan kinerja.'),
	(130, 'Recognizing & Reinforcing', 'Kemampuan untuk mengenali dan memperkuat kekuatan individu.'),
	(130, 'Identify Development Area', 'Keahlian dalam mengidentifikasi area pengembangan yang perlu diperhatikan dan memberikan saran yang bermanfaat.'),
	(130, 'Creative Process', 'Kreativitas dalam mengatur dan mengelola proses umpan balik yang efektif.'),

	(131, 'Support & Guidances', 'Kemampuan untuk membimbing, mendukung, dan memberikan nasihat kepada anggota tim atau individu dalam pengembangan keterampilan, pengetahuan, dan kompetensi.'),
	(131, 'Effective Feedback', 'Keahlian dalam memberikan umpan balik yang konstruktif dan bimbingan yang efektif.'),
	(131, 'Foster Growth', 'Kemampuan untuk mendorong pertumbuhan dan eksplorasi potensi individu.'),
	(131, 'Active Listening', 'Keterampilan dalam mendengarkan aktif dan memahami kebutuhan serta tujuan pengembangan individu.'),
	(131, 'Creative', 'Kreativitas dalam menyediakan sumber daya dan peluang pembelajaran yang relevan.'),

	(132, 'Empathic', 'memiliki kemampuan empati yang kuat, yang berarti mereka mampu memahami dan merasakan apa yang dirasakan orang lain.'),
	(132, 'Responsive', 'responsif terhadap kebutuhan dan masalah orang lain, dan berusaha untuk menanggapi dengan cepat dan efisien.'),
	(132, 'Supportive', 'berorientasi pada pelayanan dan bersedia untuk "going extra" membantu orang lain, baik itu dengan memberikan dukungan emosional atau praktikal.'),
	(132, 'Interpersonal Skills', 'melibatkan keterampilan interpersonal yang kuat, termasuk kemampuan untuk berkomunikasi dengan efektif dan bekerja dengan baik dalam tim.'),
	(132, 'Commitment', 'memiliki komitmen kuat untuk memberikan layanan atau dukungan yang berkualitas tinggi, dan berusaha untuk meningkatkan kualitas pelayanan mereka sepanjang waktu.'),

	(133, 'Customer Understanding', 'Pemahaman yang kuat tentang siapa pelanggan mereka dan apa yang mereka inginkan, dapat memahami dan memenuhi kebutuhan pelanggan, dan mampu beradaptasi terhadap perubahan preferensi pelanggan.'),
	(133, 'Customer Services', 'Kemampuan untuk menyediakan layanan pelanggan yang luar biasa, termasuk menangani pertanyaan dan keluhan pelanggan dengan cepat dan efisien, dan melakukan upaya ekstra untuk memastikan kepuasan pelanggan.'),
	(133, 'Valuing Feedback', 'Menghargai umpan balik dari pelanggan dan menggunakannya untuk meningkatkan produk, layanan, atau proses; melihat kritik sebagai peluang untuk belajar dan berkembang.'),
	(133, 'Anticipating Needs', 'Memprediksi dan merespons kebutuhan pelanggan sebelum mereka diungkapkan atau bahkan dikenali oleh pelanggan itu sendiri.'),
	(133, 'Building Relationships', 'Membangun dan mempertahankan hubungan yang kuat dengan pelanggan, berdasarkan saling percaya dan memahami.'),

	(134, 'Open Communication', 'Membangun komunikasi yang terbuka dan saling menguntungkan dengan pelanggan.'),
	(134, 'Interest & Attention', 'Menunjukkan minat dan perhatian terhadap kebutuhan dan keinginan individual pelanggan.'),
	(134, 'Indepth Understanding', 'Mengembangkan pemahaman yang mendalam tentang pelanggan dan kebutuhan mereka.'),
	(134, 'Regular Contact', 'Menjaga kontak reguler dengan pelanggan untuk memperkuat hubungan dan membangun kesetiaan.'),
	(134, 'Personalized & Customized', 'Menyediakan layanan pelanggan yang personal dan menyesuaikan untuk menciptakan pengalaman positif.'),

	(135, 'Interviews & Surveys', 'Melakukan wawancara atau survei dengan pelanggan untuk memahami kebutuhan dan harapan mereka.'),
	(135, 'Observe & Monitoring', 'Mengobservasi dan mengamati perilaku pelanggan untuk mengidentifikasi kebutuhan yang mungkin tidak terungkap secara langsung.'),
	(135, 'Analyse Customer Data', 'Menganalisis data pelanggan, seperti umpan balik, keluhan, dan tren, untuk mengidentifikasi pola kebutuhan.'),
	(135, 'Customer Journey Mapping', 'Menggunakan teknik pemetaan perjalanan pelanggan untuk memahami pengalaman pelanggan dan menemukan peluang peningkatan.'),
	(135, 'Market Research', 'Melakukan riset pasar untuk mempelajari tren industri, preferensi pelanggan, dan kebutuhan yang muncul.'),

	(136, 'Empathic Services', 'Memberikan layanan pelanggan yang ramah, responsif, dan profesional.'),
	(136, 'Understand Needs & Preferences', 'Memahami kebutuhan dan preferensi pelanggan untuk menyediakan solusi yang sesuai.'),
	(136, 'Professional Assistance', 'Menyediakan bantuan dan informasi yang akurat dan tepat waktu kepada pelanggan.'),
	(136, 'Service Consistencies', 'Menjaga konsistensi dalam pelayanan pelanggan untuk membangun kepercayaan dan kepuasan jangka panjang.'),
	(136, 'Professional Complaint Handling', 'Menangani keluhan pelanggan dengan cepat dan efektif untuk memastikan resolusi yang memuaskan.'),

	(137, 'Feedback & Surveys', 'Menggunakan metode survei dan umpan balik pelanggan untuk mengukur tingkat kepuasan.'),
	(137, 'Satisfaction Analysis', 'Menganalisis data kepuasan pelanggan untuk mengidentifikasi area yang memerlukan perbaikan.'),
	(137, 'Continuous Evaluation', 'Melakukan evaluasi berkala terhadap kualitas layanan pelanggan dan membandingkannya dengan standar yang ditetapkan.'),
	(137, 'KPI Driven', 'Menggunakan KPI untuk memantau dan mengukur kepuasan pelanggan.'),
	(137, 'Customer Involvement', 'Melibatkan pelanggan dalam proses umpan balik dan pemantauan untuk memperoleh wawasan berharga.'),

	(138, 'Change Acumen', 'Pemahaman yang kuat tentang bagaimana perubahan dapat mempengaruhi individu dan organisasi, memahami proses perubahan dan bagaimana resistensi terhadap perubahan bisa muncul dan diatasi.'),
	(138, 'Effective Communication', 'Komunikasi yang efektif tentang perubahan apa yang akan terjadi, mengapa itu penting, dan bagaimana itu akan mempengaruhi individu dan organisasi secara keseluruhan, melibatkan penjelaskan manfaat perubahan dan mendengarkan dan menanggapi kekhawatiran atau pertanyaan.'),
	(138, 'Support & Empowerment', 'Memberikan dukungan kepada orang lain saat mereka menyesuaikan diri dengan perubahan. Ini bisa melibatkan pelatihan atau pelatihan, bimbingan, atau menyediakan sumber daya untuk membantu orang mengatasi tantangan yang mungkin mereka hadapi.'),
	(138, 'Adaptability', 'Beradaptasi dengan perubahan dan menjadi fleksibel dalam menghadapi tantangan baru adalah kunci dalam manajemen perubahan. Ini melibatkan berpikir kreatif dan mencari solusi baru ketika muncul hambatan.'),
	(138, 'Change Leadership', 'Memimpin orang lain melalui perubahan, melibatkan pengambilan keputusan, memotivasi orang lain, dan menjadi peran model dalam menerima dan beradaptasi dengan perubahan.'),

	(139, 'Change Awareness', 'Kepekaan terhadap isu-isu atau masalah yang memerlukan perubahan.'),
	(139, 'Change Identification', 'Mengidentifikasi dan memahami kebutuhan untuk melakukan perubahan.'),
	(139, 'Gap & Opportunity Analysis', 'Analisa data dan informasi untuk mengidentifikasi kesenjangan atau peluang perbaikan.'),
	(139, 'Openmind', 'Menggali masukan dan umpan balik dari beragam pihak terkait.'),
	(139, 'Creative', 'Kreatifitas dalam mengidentifikasi situasi dan kebutuhan perubahan.'),

	(140, 'Comprehensive Planning', 'Merancang rencana yang komprehensif dan realistis untuk mengimplementasikan perubahan.'),
	(140, 'Role & Activity Mapping', 'Memetakan langkah-langkah, tanggung jawab, dan waktu yang diharapkan.'),
	(140, 'Resource Identification ', 'Identifikasi sumber daya yang dibutuhkan untuk mendukung perubahan.'),
	(140, 'Risk Anticipation', 'Mengantisipasi hambatan atau tantangan yang mungkin terjadi selama perubahan.'),
	(140, 'Creative', 'Kreativitas merancang strategi mitigasi risiko untuk menjaga kelancaran implementasi perubahan.'),

	(141, 'Manage Problem & Risk', 'Mengelola dan mengatasi ketidakpastian dan mengelola risiko selama proses perubahan.'),
	(141, 'Manage Concern & Doubt', 'Mengidentifikasi dan mengelola kekhawatiran dan keberatan dari anggota tim atau pihak terkait.'),
	(141, 'Manage Supportive Environment', 'Membangun dan mengelola lingkungan yang mendukung dan memberikan rasa aman selama perubahan.'),
	(141, 'Manage Risk', 'Analisa dan evaluasi risiko yang terkait dengan perubahan.'),
	(141, 'Creative', 'Kreativitas menemukan solusi yang efektif untuk mengatasi tantangan dan hambatan yang muncul.'),

	(142, 'Impact Evaluation', ' Evaluasi dampak perubahan yang telah diimplementasikan.'),
	(142, 'Control & Monitoring', 'kinerja, efisiensi, atau pencapaian tujuan setelah perubahan dilakukan.'),
	(142, 'Analyse Ongoing Change Data', 'Menganalisis beragam data terkait dengan inisiatif perubahan secara berkesinambungan dan berkelanjutan.'),
	(142, 'Reflective Learning', 'Kepekaan terhadap pelajaran yang dapat dipetik dari proses perubahan.'),
	(142, 'Creative', 'Kreativitas dalam mengidentifikasi peluang perbaikan dan peningkatan untuk pengelolaan perubahan di masa depan.'),

	(143, 'Business Acumen', 'Pemahaman komprehensif tentang operasi bisnis, mencakup keterampilan dan wawasan aspek bisnis, keuangan, pemasaran, operasi.'),
	(143, 'Supply Chain', 'Mengelola rantai pasok secara efektif untuk memastikan pasokan yang lancar dan waktu pengiriman yang tepat.'),
	(143, 'Operational Planning', 'Merencanakan operasi harian dengan efisien dan mengoptimalkan sumber daya yang tersedia.'),
	(143, 'Policy, Process & SOP', 'Mengembangkan dan menerapkan kebijakan dan prosedur operasional yang efisien.'),
	(143, 'PDCA & PICA', 'Mengawasi proses produksi dan memastikan efisiensi dan kualitas yang tinggi, evaluasi kinerja dan mengidentifikasi area perbaikan.'),

	(144, 'Market Segment', 'Menganalisis segmen pasar dan mengidentifikasi target pasar yang tepat.'),
	(144, 'Positioning & Service', 'Merumuskan strategi positioning produk atau layanan yang efektif.'),
	(144, 'Promotion', 'Mengembangkan dan melaksanakan kampanye promosi yang sesuai dengan target pasar.'),
	(144, 'Consumer Behavior', 'Memahami perilaku konsumen dan menggunakan pengetahuan tersebut untuk menginformasikan keputusan pemasaran.'),
	(144, 'Market Research', 'Melakukan riset pasar untuk mendapatkan wawasan tentang tren industri dan kebutuhan pelanggan.'),

	(145, 'Trend & Growth', 'Mengikuti tren industri terkini dan mengidentifikasi peluang pertumbuhan.'),
	(145, 'Competition', 'Memahami persaingan dalam industri dan mengidentifikasi keunggulan kompetitif.'),
	(145, 'Policy & Regulation', 'Menganalisis perubahan regulasi dan kebijakan yang dapat mempengaruhi bisnis.'),
	(145, 'Business Strategy', 'Memahami preferensi pelanggan dan memodifikasi strategi bisnis sesuai dengan kebutuhan pasar.'),
	(145, 'Technology Development', 'Mengikuti perkembangan teknologi terkait industri dan mempertimbangkan penerapan inovasi dalam bisnis.'),

	(146, 'Financial Report', 'Menganalisis laporan keuangan untuk memahami kinerja keuangan perusahaan.'),
	(146, 'Budgeting', 'Mengelola anggaran dengan efisien dan memantau pengeluaran bisnis.'),
	(146, 'Cost Efficiency', 'Memahami konsep pengendalian biaya dan mengidentifikasi peluang untuk mengurangi biaya.'),
	(146, 'Financial Analysis', 'Melakukan analisis keuangan untuk mengevaluasi investasi dan proyek bisnis.'),
	(146, 'Financial Indicators', 'Memahami indikator keuangan utama dan menggunakannya untuk mengukur kinerja keuangan.'),

	(147, 'Business Environment Analysis', 'Menganalisis lingkungan bisnis dan mengidentifikasi peluang dan ancaman.'),
	(147, 'Vision/Mission', 'Mengembangkan visi dan misi bisnis yang jelas dan mengarahkan keputusan strategis.'),
	(147, 'Business Strategy', 'Menentukan strategi kompetitif yang efektif untuk memenangkan pasar.'),
	(147, 'Key Success Factors', 'Mengidentifikasi faktor kunci keberhasilan dan mengembangkan rencana tindakan yang tepat.'),
	(147, 'Monitoring Development & Competition', 'Memantau perkembangan industri dan persaingan untuk menyesuaikan strategi bisnis.'),

	(148, 'Technology Trend', 'Mengikuti perkembangan teknologi terbaru yang relevan dengan bisnis dan industri.'),
	(148, 'Updating', 'Menghadiri diskusi, workshop, seminar untuk memperbarui pengetahuan tentang teknologi terkini.'),
	(148, 'Learning', 'Mempelajari aplikasi baru dan teknologi yang dapat meningkatkan efisiensi dan produktivitas bisnis.'),
	(148, 'Identify', 'Mengidentifikasi kebutuhan teknologi yang baru dan relevan untuk memenuhi tuntutan bisnis.'),
	(148, 'Seeking Opportunities', 'Mencari peluang penerapan teknologi baru dalam bisnis untuk meningkatkan daya saing.'),

	(149, 'Proficient', 'Behasil menggunakan perangkat lunak yang relevan dengan tugas dan pekerjaan yang diemban.'),
	(149, 'Mastery', 'Menguasai fungsi dan fitur utama dari perangkat lunak yang digunakan.'),
	(149, 'Optimizing', 'Efisien dalam mengoperasikan perangkat lunak dan memanfaatkan fungsionalitasnya secara maksimal.'),
	(149, 'Adaptability', 'Mampu menyesuaikan diri dengan perangkat lunak baru dan belajar penggunaannya dengan cepat.'),
	(149, 'Software Savvy', 'Memiliki keterampilan pemecahan masalah yang kuat terkait penggunaan perangkat lunak.'),

	(150, 'Effective Search Techniques', 'Menguasai teknik pencarian yang efektif dan menggunakan sumber daya internet dengan efisien.'),
	(150, 'Information Evaluation', 'Menilai keandalan dan kualitas informasi yang ditemukan di internet.'),
	(150, 'Understanding Copyright and Ethical Use', 'Memahami konsep hak cipta, penggunaan etis, dan kebijakan privasi saat menggunakan informasi dari internet.'),
	(150, 'Utilizing Search and Filtering Tools', 'Mampu menggunakan alat pencarian dan filterisasi yang relevan untuk memperoleh informasi yang relevan.'),
	(150, 'Understanding Internet Security', 'Memahami risiko dan ancaman yang terkait dengan keamanan internet dan mengambil tindakan pencegahan yang sesuai.'),

	(151, 'Using Digital Channels Effectively', 'Menggunakan saluran digital dengan efektif untuk berkomunikasi dengan pelanggan, rekan kerja, dan mitra bisnis.'),
	(151, 'Delivering Clear and Concise Messages', 'Menyampaikan pesan dengan jelas, singkat, dan sesuai dengan konteks komunikasi.'),
	(151, 'Understanding Digital Communication Ethics', 'Memahami etika komunikasi digital, termasuk privasi dan kebijakan penggunaan informasi.'),
	(151, 'Appropriate Style and Format', 'Menyampaikan informasi dengan gaya dan format yang sesuai untuk saluran digital yang digunakan.'),
	(151, 'Utilizing Digital Communication Tools', 'Menggunakan alat komunikasi digital, seperti email atau platform kolaborasi, dengan efisiensi dan efektivitas.'),
	(152, 'Built-in', 'TBD'),
	(153, 'Built-in', 'TBD'),
	(154, 'Built-in', 'TBD'),
	(155, 'Built-in', 'TBD'),
	(156, 'Built-in', 'TBD'),
	(157, 'Built-in', 'TBD'),
	(158, 'Built-in', 'TBD'),
	(159, 'Built-in', 'TBD');

